{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "gm6yih2qzvazfcrijednhk5dri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.7.jar",
          "url": "megamek-0.49.7.jar",
          "size": 7424176,
          "sha512": "3a0a37444586e817a9ad77919129ce7a87e3f05fe712d38072d24af87ef0981f05e5ee60a0fd9b64f9dd6ed13c06282220b846528834c2ce65c994f3597088a0",
          "sha256": "47ea49d5bb792592d85f7020bc0cb760e9283621c3d1f09cc9bfc36722682173",
          "sha1": "435344b65df5e588ad6a37b13194f7a4fef4d0a5",
          "md5": "f5a77221ae0044512dcec2165162cb14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.7.jar",
          "url": "megamek-0.49.7.jar",
          "size": 7424176,
          "sha512": "3a0a37444586e817a9ad77919129ce7a87e3f05fe712d38072d24af87ef0981f05e5ee60a0fd9b64f9dd6ed13c06282220b846528834c2ce65c994f3597088a0",
          "sha256": "47ea49d5bb792592d85f7020bc0cb760e9283621c3d1f09cc9bfc36722682173",
          "sha1": "435344b65df5e588ad6a37b13194f7a4fef4d0a5",
          "md5": "f5a77221ae0044512dcec2165162cb14"
        }
      ]
    }
  ]
}
