{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "gd56li3kqbgbnhky37pkelvm4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042080,
          "sha512": "a869717233718d604d99cff63e7d58ea9c9d1a6755bf831607a8e02b74bbad2b0cd40a64a5f27fb15ac4b86593b96a511483e98b246b1631cc74f3d3fdbd546d",
          "sha256": "e2c35f69827afd0d1c5abba5d9d9dc3abc02d5798d2026a9633de149e4849258",
          "sha1": "1ced951d6baab8d5cb81b1e0f0546f6493f497d1",
          "md5": "5bc776716bbcb9842f2d81ecf4cd8c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042080,
          "sha512": "a869717233718d604d99cff63e7d58ea9c9d1a6755bf831607a8e02b74bbad2b0cd40a64a5f27fb15ac4b86593b96a511483e98b246b1631cc74f3d3fdbd546d",
          "sha256": "e2c35f69827afd0d1c5abba5d9d9dc3abc02d5798d2026a9633de149e4849258",
          "sha1": "1ced951d6baab8d5cb81b1e0f0546f6493f497d1",
          "md5": "5bc776716bbcb9842f2d81ecf4cd8c0b"
        }
      ]
    }
  ]
}
