{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "yihhz4mvevcuhp2ssbfmxe7ybi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1044414,
          "sha512": "06ada53a4012bd45267a98423f7b2732ceaa930b7922080155c42d0b68f7df5920af01293f70d21d8373cfe52790015bf195dc2b6e4c77ce89c43ca377abcc6b",
          "sha256": "88739bf81c72079b3e69a9aa3d8a92bb24666127d906f4fd1ed638df65bb98a6",
          "sha1": "122c3cc5b21783fb96501fcd6a85071b76d95b9a",
          "md5": "ff358cb2d0e0a4c2469c1711085173b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1044414,
          "sha512": "06ada53a4012bd45267a98423f7b2732ceaa930b7922080155c42d0b68f7df5920af01293f70d21d8373cfe52790015bf195dc2b6e4c77ce89c43ca377abcc6b",
          "sha256": "88739bf81c72079b3e69a9aa3d8a92bb24666127d906f4fd1ed638df65bb98a6",
          "sha1": "122c3cc5b21783fb96501fcd6a85071b76d95b9a",
          "md5": "ff358cb2d0e0a4c2469c1711085173b8"
        }
      ]
    }
  ]
}
