{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "lliaty4ktzehjnakdh335zfo5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042268,
          "sha512": "478fff1a60a3deae0fa850b98a99aa066d122739b25096b8b1211b2306c5adb82e96ca53738f8132e0067a600ac3d2da27bc20381cf6f53d01cecae78bfa09f3",
          "sha256": "2d2c52674f5322c65256401f48e228b2828440bcc14413802dcfab11686764af",
          "sha1": "f5b4ff1e8a0b6cb456df02dede230592c8dd47c3",
          "md5": "ce480f80fbd32fe78afadd035f505d7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042268,
          "sha512": "478fff1a60a3deae0fa850b98a99aa066d122739b25096b8b1211b2306c5adb82e96ca53738f8132e0067a600ac3d2da27bc20381cf6f53d01cecae78bfa09f3",
          "sha256": "2d2c52674f5322c65256401f48e228b2828440bcc14413802dcfab11686764af",
          "sha1": "f5b4ff1e8a0b6cb456df02dede230592c8dd47c3",
          "md5": "ce480f80fbd32fe78afadd035f505d7a"
        }
      ]
    }
  ]
}
