{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "t7khhgcphzcavlno5scsmzmizq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042108,
          "sha512": "54b70c1134bfb80aa4eb646ade69e6de1c1610f8617733a4af851bc04d65e6462b92672db039a82f632d4ba3b6a86c7fa56ffc0b3911f704f1ad4798d2df901c",
          "sha256": "fffe5f332f58f558b1b9b1f7c96e95e42452cf51d4208391a54d351a2827625d",
          "sha1": "01afb01ecf0e2342e06fcaa56dba0bd33a0606d9",
          "md5": "6357ef030ab79e99dc9d86a5cfe4eb8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042108,
          "sha512": "54b70c1134bfb80aa4eb646ade69e6de1c1610f8617733a4af851bc04d65e6462b92672db039a82f632d4ba3b6a86c7fa56ffc0b3911f704f1ad4798d2df901c",
          "sha256": "fffe5f332f58f558b1b9b1f7c96e95e42452cf51d4208391a54d351a2827625d",
          "sha1": "01afb01ecf0e2342e06fcaa56dba0bd33a0606d9",
          "md5": "6357ef030ab79e99dc9d86a5cfe4eb8f"
        }
      ]
    }
  ]
}
