{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fxhvfttpvrggldkh23veyfudaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042753,
          "sha512": "85944c75d845122e4ea971bab4b9deadae4ca1fd01bfb69e1cbd738d49a94346a36e8597b1cfe2ac8db6bc935aa7166b414f61efbe0dde168d4ae7e4ea4117b7",
          "sha256": "9bccface96b1bd050570ed8c71b865d71798e35de0599b14f29a1d41dc2c408a",
          "sha1": "74938d0f097c537325809bf712185767ce973afa",
          "md5": "3c259585dd0911de161dc7be983f83db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.9-SNAPSHOT.jar",
          "url": "megameklab-0.49.9-SNAPSHOT.jar",
          "size": 1042753,
          "sha512": "85944c75d845122e4ea971bab4b9deadae4ca1fd01bfb69e1cbd738d49a94346a36e8597b1cfe2ac8db6bc935aa7166b414f61efbe0dde168d4ae7e4ea4117b7",
          "sha256": "9bccface96b1bd050570ed8c71b865d71798e35de0599b14f29a1d41dc2c408a",
          "sha1": "74938d0f097c537325809bf712185767ce973afa",
          "md5": "3c259585dd0911de161dc7be983f83db"
        }
      ]
    }
  ]
}
