{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fwgn7dklznhobneflizmtnjqha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7592653,
          "sha512": "3c799bb323c13887f5f31e0227592beb9e5af23a609beec7661c41cf581b2d2e77aa23ad942e0f359f28cf8258c89f4ca3ea37e328cf48c995c3e2f43c64d021",
          "sha256": "93f95bc0deff8edc6ce451fef54fa48c70fd7fc0efe0b0aebe0026f1ea4fe969",
          "sha1": "cc371fdae8f21675309f3906d9f75c7bf011e959",
          "md5": "351363e7adc463564d158d2d5967b49c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7592653,
          "sha512": "3c799bb323c13887f5f31e0227592beb9e5af23a609beec7661c41cf581b2d2e77aa23ad942e0f359f28cf8258c89f4ca3ea37e328cf48c995c3e2f43c64d021",
          "sha256": "93f95bc0deff8edc6ce451fef54fa48c70fd7fc0efe0b0aebe0026f1ea4fe969",
          "sha1": "cc371fdae8f21675309f3906d9f75c7bf011e959",
          "md5": "351363e7adc463564d158d2d5967b49c"
        }
      ]
    }
  ]
}
