{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "27erdw6hrrhj3n75bxdvf2laau"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7615751,
          "sha512": "340aba13704d28fad1023ad10f12c55bf78a34fd44c1bc4f01aa980f75f0fe2ac44b18a7722df151856eaf0e4d12612424267d5042ca377dec73aa60afd4290e",
          "sha256": "6f98d9c9ac79ec3b65e16fff611ea648b2caa6316b2018eeb3f6153743d7ea91",
          "sha1": "b247244594901eac1fd91912582e2f51096d650b",
          "md5": "48afff2eb83d05b8b5b893ca10b02359"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7615751,
          "sha512": "340aba13704d28fad1023ad10f12c55bf78a34fd44c1bc4f01aa980f75f0fe2ac44b18a7722df151856eaf0e4d12612424267d5042ca377dec73aa60afd4290e",
          "sha256": "6f98d9c9ac79ec3b65e16fff611ea648b2caa6316b2018eeb3f6153743d7ea91",
          "sha1": "b247244594901eac1fd91912582e2f51096d650b",
          "md5": "48afff2eb83d05b8b5b893ca10b02359"
        }
      ]
    }
  ]
}
