{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "3czvlkikdjdjvfpzvacfqzauea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7434866,
          "sha512": "1237b0e7b7ec10f908cafc8b50b275ec9483f2bdb2fc8e67e06e812d0c103fed32d3a23e60015c7f5bbda0d7462f03f8df4ed44c8a09426187d98fee90cdd5df",
          "sha256": "52c1a357f73bf12e4310287ce08dad2ae7ed78248afab4b1dff5f174da1de6e5",
          "sha1": "071377a3dfcd793ae015f1768a4e53012dcf4879",
          "md5": "0144b6b6f7e6a55461109e8faaa4475a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7434866,
          "sha512": "1237b0e7b7ec10f908cafc8b50b275ec9483f2bdb2fc8e67e06e812d0c103fed32d3a23e60015c7f5bbda0d7462f03f8df4ed44c8a09426187d98fee90cdd5df",
          "sha256": "52c1a357f73bf12e4310287ce08dad2ae7ed78248afab4b1dff5f174da1de6e5",
          "sha1": "071377a3dfcd793ae015f1768a4e53012dcf4879",
          "md5": "0144b6b6f7e6a55461109e8faaa4475a"
        }
      ]
    }
  ]
}
