{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "4q6f6jpzljg4tdewkmbncbw6ay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7465517,
          "sha512": "a0d2cf87436811efd07cb3ebf98e41cb9edb3a5f9af338437fb0d57c2b98ec52f92361d5f9fa02b66722c7f0831128418c5bb8aa660d6fc56128bd3a3c6a06fe",
          "sha256": "bd048d65ec116ae59ff84d2bbc9f501cdd9482b741d0e8e5c1aeb612eb8fa619",
          "sha1": "b468ee47a6d5a03a2b724a9775f00c40bf12b61f",
          "md5": "a9cecd8d3c29346e85fa6f9a5b371e27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7465517,
          "sha512": "a0d2cf87436811efd07cb3ebf98e41cb9edb3a5f9af338437fb0d57c2b98ec52f92361d5f9fa02b66722c7f0831128418c5bb8aa660d6fc56128bd3a3c6a06fe",
          "sha256": "bd048d65ec116ae59ff84d2bbc9f501cdd9482b741d0e8e5c1aeb612eb8fa619",
          "sha1": "b468ee47a6d5a03a2b724a9775f00c40bf12b61f",
          "md5": "a9cecd8d3c29346e85fa6f9a5b371e27"
        }
      ]
    }
  ]
}
