{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "qyqj6lzigvcsrbikdvpo7fq5ji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7598023,
          "sha512": "22767f3a0e37f74b44d19280c51c4bddf9d3c4c65a2b638af3fc8398ec7cdca6706c6128bf527135296ce4064bc958d12afd3ef3285a43cc3545cea13af049c4",
          "sha256": "28e289d4b558e87e7002466a217d7e5b56a1042ee4d9051f6cbe15c70cf1eba8",
          "sha1": "a5989afeeeb200bd37f3c4a8ea2d863ef1b044f0",
          "md5": "5fbef022bc10b38eeb0694c7d1e78bf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7598023,
          "sha512": "22767f3a0e37f74b44d19280c51c4bddf9d3c4c65a2b638af3fc8398ec7cdca6706c6128bf527135296ce4064bc958d12afd3ef3285a43cc3545cea13af049c4",
          "sha256": "28e289d4b558e87e7002466a217d7e5b56a1042ee4d9051f6cbe15c70cf1eba8",
          "sha1": "a5989afeeeb200bd37f3c4a8ea2d863ef1b044f0",
          "md5": "5fbef022bc10b38eeb0694c7d1e78bf8"
        }
      ]
    }
  ]
}
