{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "dzrjz6v5kbaodhaixcsp5qmala"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7613281,
          "sha512": "8b5cfbe43ca852779c9c39c0f56e3e2520761f3bcd6ab0c70966b631cb4341c33a16317e7622b3f726e72066de82e07c962dd54ed58cea60d0972726a7c42bee",
          "sha256": "5ba9d1d695509846c30d401ed1721aac495c4715862da11859c176a4cbc90c5a",
          "sha1": "d77417e83a4997bb5fe7891531cfd4432e8c7ae1",
          "md5": "ba60cd4fd0dd76f88dfcd8298f52a077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7613281,
          "sha512": "8b5cfbe43ca852779c9c39c0f56e3e2520761f3bcd6ab0c70966b631cb4341c33a16317e7622b3f726e72066de82e07c962dd54ed58cea60d0972726a7c42bee",
          "sha256": "5ba9d1d695509846c30d401ed1721aac495c4715862da11859c176a4cbc90c5a",
          "sha1": "d77417e83a4997bb5fe7891531cfd4432e8c7ae1",
          "md5": "ba60cd4fd0dd76f88dfcd8298f52a077"
        }
      ]
    }
  ]
}
