{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "tdusc32mwnbpzclv64cxlq7pxq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7615680,
          "sha512": "07986bd8092b56d96ef56a9f8810425d1877f3c978acbba17615cf86f61848005b996c9dc6a0bfbb546b2a7e47b176ef014db62530e57fcbd01b28955a776ba6",
          "sha256": "4aeb45bfc93845f4eb3263bc5ae75d1a43f37497bce2609431aea53d2d33bd05",
          "sha1": "6ad4e6f1828626550a7ebd4e1d5c5721a61f8920",
          "md5": "f6bb1c3ba49c8950a9069500570267b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8-SNAPSHOT.jar",
          "url": "megamek-0.49.8-SNAPSHOT.jar",
          "size": 7615680,
          "sha512": "07986bd8092b56d96ef56a9f8810425d1877f3c978acbba17615cf86f61848005b996c9dc6a0bfbb546b2a7e47b176ef014db62530e57fcbd01b28955a776ba6",
          "sha256": "4aeb45bfc93845f4eb3263bc5ae75d1a43f37497bce2609431aea53d2d33bd05",
          "sha1": "6ad4e6f1828626550a7ebd4e1d5c5721a61f8920",
          "md5": "f6bb1c3ba49c8950a9069500570267b3"
        }
      ]
    }
  ]
}
