{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19.jar",
          "url": "megamek-0.49.19.jar",
          "size": 8690422,
          "sha512": "89fbee1a635bf9a12a14effb0c8d4375b3f146209d75b383d735d9c25093aff93f7fc61add34cfb809b176a2f158e647c3b613ef9ef47f96426ba891188bb571",
          "sha256": "1bd416f571b9ba7c013eb44d3086a55f22e22d6720fdcd18a7db8d1f522ffc84",
          "sha1": "9e6152c45734c294914e0e39efaf0a6a0d240bed",
          "md5": "e608dcd56e2c08db85d75d5ab42597e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19.jar",
          "url": "megamek-0.49.19.jar",
          "size": 8690422,
          "sha512": "89fbee1a635bf9a12a14effb0c8d4375b3f146209d75b383d735d9c25093aff93f7fc61add34cfb809b176a2f158e647c3b613ef9ef47f96426ba891188bb571",
          "sha256": "1bd416f571b9ba7c013eb44d3086a55f22e22d6720fdcd18a7db8d1f522ffc84",
          "sha1": "9e6152c45734c294914e0e39efaf0a6a0d240bed",
          "md5": "e608dcd56e2c08db85d75d5ab42597e3"
        }
      ]
    }
  ]
}
