{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19.jar",
          "url": "megamek-0.49.19.jar",
          "size": 8692046,
          "sha512": "c088cf5746944e682c0c75d429733c3112d9386b115755ca439ec66c43c24d864b49c5a9a954ef886d28a1e1752ea80e7fa2da182e76be7b783d2488ab97a3dd",
          "sha256": "aa7791b8c4592920956ba274a7511a7f4fe92acf3eca35fce573a38bcec7fcbb",
          "sha1": "0d40e5d120ba010faccdf77cd42c24180819b974",
          "md5": "2eeeed3f1713b60c331d19a1f19e80d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19.jar",
          "url": "megamek-0.49.19.jar",
          "size": 8692046,
          "sha512": "c088cf5746944e682c0c75d429733c3112d9386b115755ca439ec66c43c24d864b49c5a9a954ef886d28a1e1752ea80e7fa2da182e76be7b783d2488ab97a3dd",
          "sha256": "aa7791b8c4592920956ba274a7511a7f4fe92acf3eca35fce573a38bcec7fcbb",
          "sha1": "0d40e5d120ba010faccdf77cd42c24180819b974",
          "md5": "2eeeed3f1713b60c331d19a1f19e80d3"
        }
      ]
    }
  ]
}
