{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.20-SNAPSHOT.jar",
          "url": "mekhq-0.49.20-SNAPSHOT.jar",
          "size": 4000649,
          "sha512": "eb76b600561a4aa2e017d5138795a49caf2c1f628aea1b20d489f387ca45a2488bbdcf7ed57b047a0e2e5c33ac9bb3a0b6290efbaec8e515c402d36f10b6ff20",
          "sha256": "7cc1bf37252ce1536555b51892ae91974caa80e8752d82aeb2ffa427ff63dae0",
          "sha1": "e9f1dd74a2b82290667dc676347975b2220c8f2d",
          "md5": "7e012b641cc3a6defc751e91166c95ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.20-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.20-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.20-SNAPSHOT.jar",
          "url": "mekhq-0.49.20-SNAPSHOT.jar",
          "size": 4000649,
          "sha512": "eb76b600561a4aa2e017d5138795a49caf2c1f628aea1b20d489f387ca45a2488bbdcf7ed57b047a0e2e5c33ac9bb3a0b6290efbaec8e515c402d36f10b6ff20",
          "sha256": "7cc1bf37252ce1536555b51892ae91974caa80e8752d82aeb2ffa427ff63dae0",
          "sha1": "e9f1dd74a2b82290667dc676347975b2220c8f2d",
          "md5": "7e012b641cc3a6defc751e91166c95ca"
        }
      ]
    }
  ]
}
