{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9.jar",
          "url": "megamek-0.49.9.jar",
          "size": 7772968,
          "sha512": "91300ed8ad24cf333905f4415e09e3ad2e07f8053ea803af9d9b4c3a23dcb368245f74c35151e122848262c46a0f666f52c94beeb30e847f8c06c908ede21211",
          "sha256": "1cd020c7074412d93b5a606db6328aff238313bf26acf39b42f9095ecd390085",
          "sha1": "4f850f80be9fe8d92dd30cc847bb21fefb9e673f",
          "md5": "62be60679488393fe5eb5b95d9389110"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9.jar",
          "url": "megamek-0.49.9.jar",
          "size": 7772968,
          "sha512": "91300ed8ad24cf333905f4415e09e3ad2e07f8053ea803af9d9b4c3a23dcb368245f74c35151e122848262c46a0f666f52c94beeb30e847f8c06c908ede21211",
          "sha256": "1cd020c7074412d93b5a606db6328aff238313bf26acf39b42f9095ecd390085",
          "sha1": "4f850f80be9fe8d92dd30cc847bb21fefb9e673f",
          "md5": "62be60679488393fe5eb5b95d9389110"
        }
      ]
    }
  ]
}
