{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9.jar",
          "url": "megamek-0.49.9.jar",
          "size": 7771457,
          "sha512": "27a51c1dd8b2129f241766e9f86f111105b3925eed63b2b4f2793c9bbcd8456f442f3d2431a2255bd93254e8bca5b720041abc62d745a38eafffa912fa252def",
          "sha256": "d5dd79fe2b623e5d43edb72c6fe8873c6cacc2d176dcc3e2dc6fda64928cbffd",
          "sha1": "3255e4523dbefad02645ff778e192236c74fba64",
          "md5": "5d1ddffda2b53cf2cdf32fc378aac5c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9.jar",
          "url": "megamek-0.49.9.jar",
          "size": 7771457,
          "sha512": "27a51c1dd8b2129f241766e9f86f111105b3925eed63b2b4f2793c9bbcd8456f442f3d2431a2255bd93254e8bca5b720041abc62d745a38eafffa912fa252def",
          "sha256": "d5dd79fe2b623e5d43edb72c6fe8873c6cacc2d176dcc3e2dc6fda64928cbffd",
          "sha1": "3255e4523dbefad02645ff778e192236c74fba64",
          "md5": "5d1ddffda2b53cf2cdf32fc378aac5c8"
        }
      ]
    }
  ]
}
