{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8545421,
          "sha512": "2207db5414d707e20b974a0caeb35038b722626339cdf0643fb89d9b01135e379e9469eb86687e9b698c73dacf8cd896e1db3d3fa3a48662c50a8fd130666925",
          "sha256": "8092972f1c02e590de6630630be3a13ca022e5bda22272b0d3e55412dd88c445",
          "sha1": "829fd2afb0953ed3f8199e424e24b64148b274a9",
          "md5": "c9fe36e0fe13515e89e2216d6852931a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8545421,
          "sha512": "2207db5414d707e20b974a0caeb35038b722626339cdf0643fb89d9b01135e379e9469eb86687e9b698c73dacf8cd896e1db3d3fa3a48662c50a8fd130666925",
          "sha256": "8092972f1c02e590de6630630be3a13ca022e5bda22272b0d3e55412dd88c445",
          "sha1": "829fd2afb0953ed3f8199e424e24b64148b274a9",
          "md5": "c9fe36e0fe13515e89e2216d6852931a"
        }
      ]
    }
  ]
}
