{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8544882,
          "sha512": "4d08ec33e2ecfb1d7365132448364c6add167f82530975e22de9738c8084e718f20f32af22caaebaf76a91332596f80b9493ea1a6fbded8a4a45d792d700ebdd",
          "sha256": "6fe095044be924ba172bc3b5496319ef62aee3917b1f57f72b05c32631823d9c",
          "sha1": "bf9145db094f25f31626695a76da3f0b27c0829f",
          "md5": "b382c1a807c14fd5fb411e70c0ac81db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8544882,
          "sha512": "4d08ec33e2ecfb1d7365132448364c6add167f82530975e22de9738c8084e718f20f32af22caaebaf76a91332596f80b9493ea1a6fbded8a4a45d792d700ebdd",
          "sha256": "6fe095044be924ba172bc3b5496319ef62aee3917b1f57f72b05c32631823d9c",
          "sha1": "bf9145db094f25f31626695a76da3f0b27c0829f",
          "md5": "b382c1a807c14fd5fb411e70c0ac81db"
        }
      ]
    }
  ]
}
