{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8546750,
          "sha512": "c009bc1db3f08dc6659bc8be3de81e716614d5e3ac86e4c678dc058b14d6195de97cc7cf0e3c3b3f108b708d364f68c6be15e07368a1d092664bdff9ee5756cd",
          "sha256": "3edb1a703869ba86bc77c210cb5af12c221f58a32e948a4a09a28b1919e79e70",
          "sha1": "98ad527d287db1e359f08b91a948b78f04d8724a",
          "md5": "becb28960ee8ae9863de34f7a8773a3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8546750,
          "sha512": "c009bc1db3f08dc6659bc8be3de81e716614d5e3ac86e4c678dc058b14d6195de97cc7cf0e3c3b3f108b708d364f68c6be15e07368a1d092664bdff9ee5756cd",
          "sha256": "3edb1a703869ba86bc77c210cb5af12c221f58a32e948a4a09a28b1919e79e70",
          "sha1": "98ad527d287db1e359f08b91a948b78f04d8724a",
          "md5": "becb28960ee8ae9863de34f7a8773a3f"
        }
      ]
    }
  ]
}
