{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8550226,
          "sha512": "be5ab55ae4dbd4f53417d79fd4677451bfea525b9bc4a7f46036b745b9e1f8c4ee1f5d484fb58bf4ab35d0c55ba248d54a924ccec0c37fb30fcd60525abeb3ba",
          "sha256": "dec779a46c4579b222c9e08429cde1d54323288377aa60d367999eb045750dec",
          "sha1": "2cc46363c8a7cf651da3dd6931c26af9fba2c16f",
          "md5": "554a23b9646a2e4ab2dbf4d067d1bee5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.18-SNAPSHOT.jar",
          "url": "megamek-0.49.18-SNAPSHOT.jar",
          "size": 8550226,
          "sha512": "be5ab55ae4dbd4f53417d79fd4677451bfea525b9bc4a7f46036b745b9e1f8c4ee1f5d484fb58bf4ab35d0c55ba248d54a924ccec0c37fb30fcd60525abeb3ba",
          "sha256": "dec779a46c4579b222c9e08429cde1d54323288377aa60d367999eb045750dec",
          "sha1": "2cc46363c8a7cf651da3dd6931c26af9fba2c16f",
          "md5": "554a23b9646a2e4ab2dbf4d067d1bee5"
        }
      ]
    }
  ]
}
