{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.17-SNAPSHOT.jar",
          "url": "megamek-0.49.17-SNAPSHOT.jar",
          "size": 8497104,
          "sha512": "e864c1c89d1fb7aa82926621bcc93070f45448d8fad5cdc40c84f63c75fc5677edf3e77b9982a8cde5cac9784993665340a3669c5ba57a7ad11e5ef513210d56",
          "sha256": "c270add09c4140f7597677649d7cc3f3b8659ef54a5ec297038d80a260e19baa",
          "sha1": "66fb412edab64a0c55069e0f1830f9e2fbba9bbd",
          "md5": "b2a0ab6fe34768f373a727e85cf01b31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.17-SNAPSHOT.jar",
          "url": "megamek-0.49.17-SNAPSHOT.jar",
          "size": 8497104,
          "sha512": "e864c1c89d1fb7aa82926621bcc93070f45448d8fad5cdc40c84f63c75fc5677edf3e77b9982a8cde5cac9784993665340a3669c5ba57a7ad11e5ef513210d56",
          "sha256": "c270add09c4140f7597677649d7cc3f3b8659ef54a5ec297038d80a260e19baa",
          "sha1": "66fb412edab64a0c55069e0f1830f9e2fbba9bbd",
          "md5": "b2a0ab6fe34768f373a727e85cf01b31"
        }
      ]
    }
  ]
}
