{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.17-SNAPSHOT.jar",
          "url": "megamek-0.49.17-SNAPSHOT.jar",
          "size": 8498660,
          "sha512": "086c995bd1aa5062669850c838544aad8e6633e750193b71ce54cb172ebe395810842d61dcfec21ed491714482de3a0ad2c5a33622e693dae8fd5759fda593f4",
          "sha256": "e6a17717e678ed5c5fb7eb54ac82a00f55124fbb758532b2c46e4c859a9a5c4a",
          "sha1": "9be181b8e855148e38a8cbe0b93bc90d9e1dffe2",
          "md5": "9d9029b07b20a3602d71e03949dcac2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.17-SNAPSHOT.jar",
          "url": "megamek-0.49.17-SNAPSHOT.jar",
          "size": 8498660,
          "sha512": "086c995bd1aa5062669850c838544aad8e6633e750193b71ce54cb172ebe395810842d61dcfec21ed491714482de3a0ad2c5a33622e693dae8fd5759fda593f4",
          "sha256": "e6a17717e678ed5c5fb7eb54ac82a00f55124fbb758532b2c46e4c859a9a5c4a",
          "sha1": "9be181b8e855148e38a8cbe0b93bc90d9e1dffe2",
          "md5": "9d9029b07b20a3602d71e03949dcac2b"
        }
      ]
    }
  ]
}
