{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.17-SNAPSHOT.jar",
          "url": "megamek-0.49.17-SNAPSHOT.jar",
          "size": 8497059,
          "sha512": "c753b38493b9a4394aaf777f06bc08b3bbe7716c2f2facd8b2aa08b485b711d0169f85dcdd228740bdbf0bee06db8055ce21ed4c0b442f689e5ba30ef47ebab6",
          "sha256": "e504b8657bdbdb54e99cb6292d93d61c1f07e879e4004f6b224f0a4c90fad689",
          "sha1": "5e314885bb51d5729bc16c9410a1696fa010c1e9",
          "md5": "0659de914e5d021cf2c9c43d90fe8533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.17-SNAPSHOT.jar",
          "url": "megamek-0.49.17-SNAPSHOT.jar",
          "size": 8497059,
          "sha512": "c753b38493b9a4394aaf777f06bc08b3bbe7716c2f2facd8b2aa08b485b711d0169f85dcdd228740bdbf0bee06db8055ce21ed4c0b442f689e5ba30ef47ebab6",
          "sha256": "e504b8657bdbdb54e99cb6292d93d61c1f07e879e4004f6b224f0a4c90fad689",
          "sha1": "5e314885bb51d5729bc16c9410a1696fa010c1e9",
          "md5": "0659de914e5d021cf2c9c43d90fe8533"
        }
      ]
    }
  ]
}
