{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "bxn7j4umyfexfmkvmbfxjucjbq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7423089,
          "sha512": "1ba08a7d6cab90485be2094ebc75900f9e622e23d318ad2522522a4cf06c014b9ecfd9fc17d37a091fa7335b279f7c6349fa2cd33ce1596c6a02fc8185d5bae0",
          "sha256": "4dc84f242fa73f2904e728f344a129a19d02cb53599a9e20d610813e9c63f10d",
          "sha1": "e72da487082331f99597fe824a22418be0f908bd",
          "md5": "43f5dc0f58b058972e2f7e66a649426e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7423089,
          "sha512": "1ba08a7d6cab90485be2094ebc75900f9e622e23d318ad2522522a4cf06c014b9ecfd9fc17d37a091fa7335b279f7c6349fa2cd33ce1596c6a02fc8185d5bae0",
          "sha256": "4dc84f242fa73f2904e728f344a129a19d02cb53599a9e20d610813e9c63f10d",
          "sha1": "e72da487082331f99597fe824a22418be0f908bd",
          "md5": "43f5dc0f58b058972e2f7e66a649426e"
        }
      ]
    }
  ]
}
