{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "imevy42pwfd3jj7evyfyu77apy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7391832,
          "sha512": "d1f94d8e2d9ef731a1fa47c98c46a47a81c7ccf8562bde604f82c8f3c7661a082407807b735b610b41de1a401fbdfb2e567a8547003cd4fb796b8d8c8edfb1e8",
          "sha256": "590747df24f91570fb5b0a83fae3220b2a97d148b5605245fc5088444660c0a7",
          "sha1": "4d9e7206f40144c7da89b205e61ed146e1c697c8",
          "md5": "2b85b1c27b053454857d5816b9658fb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7391832,
          "sha512": "d1f94d8e2d9ef731a1fa47c98c46a47a81c7ccf8562bde604f82c8f3c7661a082407807b735b610b41de1a401fbdfb2e567a8547003cd4fb796b8d8c8edfb1e8",
          "sha256": "590747df24f91570fb5b0a83fae3220b2a97d148b5605245fc5088444660c0a7",
          "sha1": "4d9e7206f40144c7da89b205e61ed146e1c697c8",
          "md5": "2b85b1c27b053454857d5816b9658fb5"
        }
      ]
    }
  ]
}
