{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "56xjhvnesbafdgvmhvo4jgrx5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7422928,
          "sha512": "d67ee6f94ee43db6a5640502a2f25e35df726d3c4a609a147f737bb4ef1608380058528e9f575f0f108cdc834d8c5daf7e08050d4fd550d8ebec7646f703e81a",
          "sha256": "e7c3d136b7aa1a76acd4fac011823c452652e3438981f826719576ea98db5887",
          "sha1": "b90cfd3e16537f759d5756e0d3d26fa0dce74bf6",
          "md5": "3d5756f0cea9277dd113a2caf6eb05b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7422928,
          "sha512": "d67ee6f94ee43db6a5640502a2f25e35df726d3c4a609a147f737bb4ef1608380058528e9f575f0f108cdc834d8c5daf7e08050d4fd550d8ebec7646f703e81a",
          "sha256": "e7c3d136b7aa1a76acd4fac011823c452652e3438981f826719576ea98db5887",
          "sha1": "b90cfd3e16537f759d5756e0d3d26fa0dce74bf6",
          "md5": "3d5756f0cea9277dd113a2caf6eb05b6"
        }
      ]
    }
  ]
}
