{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xlnky5il5zhltlww443fgxql7q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7393193,
          "sha512": "e22681e9a47e0b79c7d9b82a7988f983025c65f6361ea33cc6fb3d047a8acd70e2824e61478577f992845428b69d712582a6d29a4d93f929ebdebd2392adf641",
          "sha256": "629840d7fec2ac272d2e08b0697a14eeb7a7fe08be44c18388a01029e2f10c95",
          "sha1": "25487eb14d4ac320828c5196a161c72df7c1fa0e",
          "md5": "beca2a84341eaacaaae2373b5918c5a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7393193,
          "sha512": "e22681e9a47e0b79c7d9b82a7988f983025c65f6361ea33cc6fb3d047a8acd70e2824e61478577f992845428b69d712582a6d29a4d93f929ebdebd2392adf641",
          "sha256": "629840d7fec2ac272d2e08b0697a14eeb7a7fe08be44c18388a01029e2f10c95",
          "sha1": "25487eb14d4ac320828c5196a161c72df7c1fa0e",
          "md5": "beca2a84341eaacaaae2373b5918c5a4"
        }
      ]
    }
  ]
}
