{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ddpgdjtrm5dwhljesd2nsbs5i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7391497,
          "sha512": "ba60a3504cef69a1645329ea47b42b48f26791a081b90972eee4c3fb00583499509a5ab2a65f1069a545a311daa92253ee874d4e0ea8071367fd4ca9d33d6ff7",
          "sha256": "976689ae0102e4803e5777e8f20a812e8a1006bdda76ea5d9c8a3c62ed383473",
          "sha1": "b283f2a4ad8c923e9baa32cd577ce893519a2d31",
          "md5": "eaa567ae39423c5ec88be6912f31c4d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.7-SNAPSHOT.jar",
          "url": "megamek-0.49.7-SNAPSHOT.jar",
          "size": 7391497,
          "sha512": "ba60a3504cef69a1645329ea47b42b48f26791a081b90972eee4c3fb00583499509a5ab2a65f1069a545a311daa92253ee874d4e0ea8071367fd4ca9d33d6ff7",
          "sha256": "976689ae0102e4803e5777e8f20a812e8a1006bdda76ea5d9c8a3c62ed383473",
          "sha1": "b283f2a4ad8c923e9baa32cd577ce893519a2d31",
          "md5": "eaa567ae39423c5ec88be6912f31c4d4"
        }
      ]
    }
  ]
}
