{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12.jar",
          "url": "megamek-0.49.12.jar",
          "size": 8328819,
          "sha512": "f8133ba80f390053bd50bfd1fb3f8631e82ff1256d4641d928627ddf109d4829e2ba9875a09e330f167b85eb3cbce5ea44a62f0fd3ed02a4df280a960e7f34c2",
          "sha256": "9b3c2d86bcfe04345ab7bf72172ba7886bb7e216c7767bd10def285e4293abb3",
          "sha1": "ec916936f830d96ee787cf84b4c4959a226fd34b",
          "md5": "c8fdb00bce2954adfae0e8af975fe966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12.jar",
          "url": "megamek-0.49.12.jar",
          "size": 8328819,
          "sha512": "f8133ba80f390053bd50bfd1fb3f8631e82ff1256d4641d928627ddf109d4829e2ba9875a09e330f167b85eb3cbce5ea44a62f0fd3ed02a4df280a960e7f34c2",
          "sha256": "9b3c2d86bcfe04345ab7bf72172ba7886bb7e216c7767bd10def285e4293abb3",
          "sha1": "ec916936f830d96ee787cf84b4c4959a226fd34b",
          "md5": "c8fdb00bce2954adfae0e8af975fe966"
        }
      ]
    }
  ]
}
