{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12.jar",
          "url": "megamek-0.49.12.jar",
          "size": 8327281,
          "sha512": "7ddd2e83d02b77ea9416e88a500d37b63f14e17c5ad24d45b4ece15df428350a28f49dc1b6c14d507dfefeb8ad3b9f8490c36aafbf895ee97178b5ae4a607434",
          "sha256": "9467e1eb09cf0387101b2da72ad302ebbf9329a4107ee18ffe50baa8cc48bb56",
          "sha1": "cf767a229a6d5551b6c0b84102162fa26b724dd2",
          "md5": "4f607b742c18020c243c8e284a37fdeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12.jar",
          "url": "megamek-0.49.12.jar",
          "size": 8327281,
          "sha512": "7ddd2e83d02b77ea9416e88a500d37b63f14e17c5ad24d45b4ece15df428350a28f49dc1b6c14d507dfefeb8ad3b9f8490c36aafbf895ee97178b5ae4a607434",
          "sha256": "9467e1eb09cf0387101b2da72ad302ebbf9329a4107ee18ffe50baa8cc48bb56",
          "sha1": "cf767a229a6d5551b6c0b84102162fa26b724dd2",
          "md5": "4f607b742c18020c243c8e284a37fdeb"
        }
      ]
    }
  ]
}
