{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.10-SNAPSHOT.jar",
          "url": "megameklab-0.49.10-SNAPSHOT.jar",
          "size": 1045421,
          "sha512": "27f35534951c7d9596730fdb68eff2ea665ab03a78a3aaf48ff71cb667369087c0d26f96d42a96a8b52d4fa1e9c4b2449dbe45c84023f9b38e6aa9227fa0590f",
          "sha256": "c5f61cb4de8bd03c0f35f84c4733f207f5e8d997c170d5cedd49868bc85afc6d",
          "sha1": "e7dcfce0ede092f744f07170a0e618029ec7c481",
          "md5": "5ee264966e867dc0fafff24b22e3da44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.10-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.10-SNAPSHOT.jar",
          "url": "megameklab-0.49.10-SNAPSHOT.jar",
          "size": 1045421,
          "sha512": "27f35534951c7d9596730fdb68eff2ea665ab03a78a3aaf48ff71cb667369087c0d26f96d42a96a8b52d4fa1e9c4b2449dbe45c84023f9b38e6aa9227fa0590f",
          "sha256": "c5f61cb4de8bd03c0f35f84c4733f207f5e8d997c170d5cedd49868bc85afc6d",
          "sha1": "e7dcfce0ede092f744f07170a0e618029ec7c481",
          "md5": "5ee264966e867dc0fafff24b22e3da44"
        }
      ]
    }
  ]
}
