{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13.jar",
          "url": "megamek-0.49.13.jar",
          "size": 8434758,
          "sha512": "f36344f112df2ae2f29b416aa0ecb7e667b79e2ed7f7a8ea1d679eb8021cc121579a4547b05c0c1ea91e12a6a9d89599afd54ab85eae5659571ce91fb02de292",
          "sha256": "06ea235c651c60bdb343357c6a1dd5efe29c89279a41fc7b2d5f4b5b38ae6855",
          "sha1": "9297affe68a71ef8fff1c7b36cbcd7fdadc542ec",
          "md5": "8d02e1fcd65fa0af9e3cd7367566f5d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13.jar",
          "url": "megamek-0.49.13.jar",
          "size": 8434758,
          "sha512": "f36344f112df2ae2f29b416aa0ecb7e667b79e2ed7f7a8ea1d679eb8021cc121579a4547b05c0c1ea91e12a6a9d89599afd54ab85eae5659571ce91fb02de292",
          "sha256": "06ea235c651c60bdb343357c6a1dd5efe29c89279a41fc7b2d5f4b5b38ae6855",
          "sha1": "9297affe68a71ef8fff1c7b36cbcd7fdadc542ec",
          "md5": "8d02e1fcd65fa0af9e3cd7367566f5d3"
        }
      ]
    }
  ]
}
