{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13.jar",
          "url": "megamek-0.49.13.jar",
          "size": 8433142,
          "sha512": "f6ad1a4d6b19824fa67fd5e0e33dc7bc06a9f885f95e796a9582c0023c2853eed3eea4d3575bbda33d2f78fdb77301b75acecb62e3bf8a5414790eb23d41ffc0",
          "sha256": "57648aefb4a32be7ced4f97039cc2c884287bd638190e1665349fd2393dd2c13",
          "sha1": "5e261a4ae1313f1d0fc844df389dc48df5757d4b",
          "md5": "8b7a288454099370ba4edfcf5eeb0ab0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13.jar",
          "url": "megamek-0.49.13.jar",
          "size": 8433142,
          "sha512": "f6ad1a4d6b19824fa67fd5e0e33dc7bc06a9f885f95e796a9582c0023c2853eed3eea4d3575bbda33d2f78fdb77301b75acecb62e3bf8a5414790eb23d41ffc0",
          "sha256": "57648aefb4a32be7ced4f97039cc2c884287bd638190e1665349fd2393dd2c13",
          "sha1": "5e261a4ae1313f1d0fc844df389dc48df5757d4b",
          "md5": "8b7a288454099370ba4edfcf5eeb0ab0"
        }
      ]
    }
  ]
}
