{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "vueuashgobasdgymtx3bfrr52q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.8.jar",
          "url": "mekhq-0.49.8.jar",
          "size": 3864143,
          "sha512": "46503246e0f0917fc8a73119f281df94381f22e184f61ca568aa5677c5fff25707f8666c7c278f7216a493f989bfe9876c57d3561cb1b3e8a30c43d127a4ea05",
          "sha256": "08e542aae23164631659cc0ce9aa099bd03f7468af98344fe88f9c58425ccd7a",
          "sha1": "1f4044f2e98fefa7362a5742de4f583491e8bdc2",
          "md5": "9ce71b0db53c47626b7234993d28b183"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.8"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.8"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.14"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.8.jar",
          "url": "mekhq-0.49.8.jar",
          "size": 3864143,
          "sha512": "46503246e0f0917fc8a73119f281df94381f22e184f61ca568aa5677c5fff25707f8666c7c278f7216a493f989bfe9876c57d3561cb1b3e8a30c43d127a4ea05",
          "sha256": "08e542aae23164631659cc0ce9aa099bd03f7468af98344fe88f9c58425ccd7a",
          "sha1": "1f4044f2e98fefa7362a5742de4f583491e8bdc2",
          "md5": "9ce71b0db53c47626b7234993d28b183"
        }
      ]
    }
  ]
}
