{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.13-SNAPSHOT.jar",
          "url": "megameklab-0.49.13-SNAPSHOT.jar",
          "size": 1061194,
          "sha512": "e59bc985e9a73582a05e02e7f3b4aa8fdb3c57045688d7cdcf295306f596f2ac102addce52cb6c1f696c1f8c5cea9be4b2ddadf17e77f9f5a833968ec7dd68b7",
          "sha256": "689f4b5b56b94b3449288e0241fc5448c0808f66648d6e8405c204394f6222a7",
          "sha1": "9cd0a1b58d91488e74de5630602245df6b05fa28",
          "md5": "842ab404a0d3a5c427f9c86c32bed50b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.13-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.13-SNAPSHOT.jar",
          "url": "megameklab-0.49.13-SNAPSHOT.jar",
          "size": 1061194,
          "sha512": "e59bc985e9a73582a05e02e7f3b4aa8fdb3c57045688d7cdcf295306f596f2ac102addce52cb6c1f696c1f8c5cea9be4b2ddadf17e77f9f5a833968ec7dd68b7",
          "sha256": "689f4b5b56b94b3449288e0241fc5448c0808f66648d6e8405c204394f6222a7",
          "sha1": "9cd0a1b58d91488e74de5630602245df6b05fa28",
          "md5": "842ab404a0d3a5c427f9c86c32bed50b"
        }
      ]
    }
  ]
}
