{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.13-SNAPSHOT.jar",
          "url": "megameklab-0.49.13-SNAPSHOT.jar",
          "size": 1056480,
          "sha512": "9ef163c49ccce46cac74acd9b0765d03973bcd21709c8bd8823dda125b0d5348baf5f053ab527f01df0bf4f65e823ae235449fc43dda0682dfdf279761cbf111",
          "sha256": "b5f337686bacab036c982c2d4cc99495925880096c200a6ebdfc74e8b8bde237",
          "sha1": "8fd1d28ea1d8a65b982b0fb68f844c47e71be13d",
          "md5": "967f957d5cc3248524f5f1df1f9dce0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.13-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.13-SNAPSHOT.jar",
          "url": "megameklab-0.49.13-SNAPSHOT.jar",
          "size": 1056480,
          "sha512": "9ef163c49ccce46cac74acd9b0765d03973bcd21709c8bd8823dda125b0d5348baf5f053ab527f01df0bf4f65e823ae235449fc43dda0682dfdf279761cbf111",
          "sha256": "b5f337686bacab036c982c2d4cc99495925880096c200a6ebdfc74e8b8bde237",
          "sha1": "8fd1d28ea1d8a65b982b0fb68f844c47e71be13d",
          "md5": "967f957d5cc3248524f5f1df1f9dce0b"
        }
      ]
    }
  ]
}
