{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "f4zd34txgbdllpwkfthmq46nri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.8.jar",
          "url": "megamek-0.49.8.jar",
          "size": 7611193,
          "sha512": "ac280154ab6ffd2b3a586e4501a3be0b31628aef3b853d29f08b9cf07a96bd8a26c524fb6fc621f56af2133a4d64dfeb2795218a59ab58bdc4e8797516a19662",
          "sha256": "05846f78ee808860504f6a1d6207029ef4df55569169e9c27e0e24ce2fb90b44",
          "sha1": "f73d62b083991c730543c13a2b68868a9c5148d1",
          "md5": "80898b9b16922fa89910b4ad6f26bb83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.8.jar",
          "url": "megamek-0.49.8.jar",
          "size": 7611193,
          "sha512": "ac280154ab6ffd2b3a586e4501a3be0b31628aef3b853d29f08b9cf07a96bd8a26c524fb6fc621f56af2133a4d64dfeb2795218a59ab58bdc4e8797516a19662",
          "sha256": "05846f78ee808860504f6a1d6207029ef4df55569169e9c27e0e24ce2fb90b44",
          "sha1": "f73d62b083991c730543c13a2b68868a9c5148d1",
          "md5": "80898b9b16922fa89910b4ad6f26bb83"
        }
      ]
    }
  ]
}
