{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.14-SNAPSHOT.jar",
          "url": "megameklab-0.49.14-SNAPSHOT.jar",
          "size": 1061510,
          "sha512": "9f23156a51ad7562dd2473a462f97b55407d5398e1f917f76a5a3aec52895451f0c4bb04322450939f0711767cb9f68fad36ea573eaefbc705c2ec5e17debbb6",
          "sha256": "0a5f4c2bbf747f17834e6fe7f1ab453b43b816e0eb529f0ac8a81d9744e1ee4e",
          "sha1": "bcc4c36617fc2c1e8e042cabf172d6388f66a8cc",
          "md5": "e005c45fe7b115ab39cd838bed90808f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.14-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.14-SNAPSHOT.jar",
          "url": "megameklab-0.49.14-SNAPSHOT.jar",
          "size": 1061510,
          "sha512": "9f23156a51ad7562dd2473a462f97b55407d5398e1f917f76a5a3aec52895451f0c4bb04322450939f0711767cb9f68fad36ea573eaefbc705c2ec5e17debbb6",
          "sha256": "0a5f4c2bbf747f17834e6fe7f1ab453b43b816e0eb529f0ac8a81d9744e1ee4e",
          "sha1": "bcc4c36617fc2c1e8e042cabf172d6388f66a8cc",
          "md5": "e005c45fe7b115ab39cd838bed90808f"
        }
      ]
    }
  ]
}
