{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.14-SNAPSHOT.jar",
          "url": "megameklab-0.49.14-SNAPSHOT.jar",
          "size": 1060918,
          "sha512": "0de1007e6550a0943dab8dfc45d41d7e565e5ed2896a1419832fc77551dbf984f561c66a5ccdfa7e7939f877c2f6030a69994962a97740d6fbb1bf747a1abc3d",
          "sha256": "115191a04cedbead5d934f6ff2abc216d5f293661890173ec3f77d53c70de4f4",
          "sha1": "78b8f6d7ebd10671a2f2c4031356d4532e149c64",
          "md5": "40acf272d00224a964ea40ba79f63ac1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.14-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.14-SNAPSHOT.jar",
          "url": "megameklab-0.49.14-SNAPSHOT.jar",
          "size": 1060918,
          "sha512": "0de1007e6550a0943dab8dfc45d41d7e565e5ed2896a1419832fc77551dbf984f561c66a5ccdfa7e7939f877c2f6030a69994962a97740d6fbb1bf747a1abc3d",
          "sha256": "115191a04cedbead5d934f6ff2abc216d5f293661890173ec3f77d53c70de4f4",
          "sha1": "78b8f6d7ebd10671a2f2c4031356d4532e149c64",
          "md5": "40acf272d00224a964ea40ba79f63ac1"
        }
      ]
    }
  ]
}
