{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.14-SNAPSHOT.jar",
          "url": "megameklab-0.49.14-SNAPSHOT.jar",
          "size": 1061353,
          "sha512": "2aaee6c4d84f5244249aedf2287de40a5cfce1750677ac476daf7933da4bf157968aea4c9b8be8978bedcd1d2e0d9ed236e21ea3990d4ef6d09f4e33a186988c",
          "sha256": "92175ec3ad4d7918e0aab25e4ceea3d3863a5261d103a9f3294e38bad6255fe6",
          "sha1": "775d86714f20f6f8b8703d43fc0684d3e52b88bc",
          "md5": "e6cc99d0cfa7ae80b788f5cbd1a708a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.14-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.14-SNAPSHOT.jar",
          "url": "megameklab-0.49.14-SNAPSHOT.jar",
          "size": 1061353,
          "sha512": "2aaee6c4d84f5244249aedf2287de40a5cfce1750677ac476daf7933da4bf157968aea4c9b8be8978bedcd1d2e0d9ed236e21ea3990d4ef6d09f4e33a186988c",
          "sha256": "92175ec3ad4d7918e0aab25e4ceea3d3863a5261d103a9f3294e38bad6255fe6",
          "sha1": "775d86714f20f6f8b8703d43fc0684d3e52b88bc",
          "md5": "e6cc99d0cfa7ae80b788f5cbd1a708a6"
        }
      ]
    }
  ]
}
