{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.14.jar",
          "url": "megamek-0.49.14.jar",
          "size": 8491013,
          "sha512": "2b536bdc28eb0f048942be0d41825fc40302bf1c3c729b2059679725fdbf5ee8eaeaf53b9a565f9386427a98c496e24d9731f94cb04e688c30ee8f6901aa5156",
          "sha256": "985a97247e59d0f22323c24d9a888c4ab45eb612303d16973d04784090ede975",
          "sha1": "5fdc5a1bff60c678fd1f9cd34bd4399bb15475fd",
          "md5": "7e80a92cd3cf2f424f0d8932ce27e983"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.14.jar",
          "url": "megamek-0.49.14.jar",
          "size": 8491013,
          "sha512": "2b536bdc28eb0f048942be0d41825fc40302bf1c3c729b2059679725fdbf5ee8eaeaf53b9a565f9386427a98c496e24d9731f94cb04e688c30ee8f6901aa5156",
          "sha256": "985a97247e59d0f22323c24d9a888c4ab45eb612303d16973d04784090ede975",
          "sha1": "5fdc5a1bff60c678fd1f9cd34bd4399bb15475fd",
          "md5": "7e80a92cd3cf2f424f0d8932ce27e983"
        }
      ]
    }
  ]
}
