{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.12-SNAPSHOT.jar",
          "url": "mekhq-0.49.12-SNAPSHOT.jar",
          "size": 3895946,
          "sha512": "00ec6f412e7eecf6136ed13abd8bf95afbec9655fe6d98ee4980c7b9b743d0dbeb2f8d6312d8d04b71a068784cc34eb7150c89bdd9bf1a5dc8c55e81f3136bfc",
          "sha256": "5ac66decc8e4632e66ed01689f96a02e529b981aa2df575cc9346ea42ea16990",
          "sha1": "d0f2d265c0f6a5151199e651064076c6139db019",
          "md5": "9a07109ded87e1f28f199e4c78d15165"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.12-SNAPSHOT.jar",
          "url": "mekhq-0.49.12-SNAPSHOT.jar",
          "size": 3895946,
          "sha512": "00ec6f412e7eecf6136ed13abd8bf95afbec9655fe6d98ee4980c7b9b743d0dbeb2f8d6312d8d04b71a068784cc34eb7150c89bdd9bf1a5dc8c55e81f3136bfc",
          "sha256": "5ac66decc8e4632e66ed01689f96a02e529b981aa2df575cc9346ea42ea16990",
          "sha1": "d0f2d265c0f6a5151199e651064076c6139db019",
          "md5": "9a07109ded87e1f28f199e4c78d15165"
        }
      ]
    }
  ]
}
