{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "yjnuxb2hkjcqncnlggyfommlc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6.jar",
          "url": "megamek-0.49.6.jar",
          "size": 7394628,
          "sha512": "f27bac2c3495297fe551c225cb9bf01592497e4b229065c43d3c7018b42ef685d9171888f99f9320ceaae22277d56381568e323f1adb5bcf14c6dbd00c6809f6",
          "sha256": "2c6ef6ff4612cfe3616a7c8ccdfb9e7641f09dd14e3577abce56641adab33a18",
          "sha1": "f8f45d98dc21aea7eca3c84b10841859fa6e8b0f",
          "md5": "c455ee1b8ca08dfb17781f4f01589462"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6.jar",
          "url": "megamek-0.49.6.jar",
          "size": 7394628,
          "sha512": "f27bac2c3495297fe551c225cb9bf01592497e4b229065c43d3c7018b42ef685d9171888f99f9320ceaae22277d56381568e323f1adb5bcf14c6dbd00c6809f6",
          "sha256": "2c6ef6ff4612cfe3616a7c8ccdfb9e7641f09dd14e3577abce56641adab33a18",
          "sha1": "f8f45d98dc21aea7eca3c84b10841859fa6e8b0f",
          "md5": "c455ee1b8ca08dfb17781f4f01589462"
        }
      ]
    }
  ]
}
