{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.11.jar",
          "url": "mekhq-0.49.11.jar",
          "size": 3895946,
          "sha512": "e3893006d5a9c70b820f3cd3d6e72d3db8024f34242d55b21f80b9f434ebbfcb768f1cea53e70ffaada2a285ae68bc222600afe28cd4464c54ac3a1478bcbfa6",
          "sha256": "396bf1ff920bc746b23331faf883f283cc66bf4da6971c508770739e44a8fc08",
          "sha1": "0c7702335b917d48b47956f963a43dc2fe5ce595",
          "md5": "50a458106bd9a05f92aa160f4003fc77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.11"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.11"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.11.jar",
          "url": "mekhq-0.49.11.jar",
          "size": 3895946,
          "sha512": "e3893006d5a9c70b820f3cd3d6e72d3db8024f34242d55b21f80b9f434ebbfcb768f1cea53e70ffaada2a285ae68bc222600afe28cd4464c54ac3a1478bcbfa6",
          "sha256": "396bf1ff920bc746b23331faf883f283cc66bf4da6971c508770739e44a8fc08",
          "sha1": "0c7702335b917d48b47956f963a43dc2fe5ce595",
          "md5": "50a458106bd9a05f92aa160f4003fc77"
        }
      ]
    }
  ]
}
