{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.14.jar",
          "url": "megameklab-0.49.14.jar",
          "size": 1064720,
          "sha512": "6be128188d99cc62c2ef1db51b0f7371bf187d6a20333a4d35a9063a08e12f6161c666ec35301d0fbfb3cf8d9413d9067ff2a5eeb84460abc2ec3354becb0e24",
          "sha256": "b61f75633b9f6da0cbdb96d6f8a40432ec9d40b127d06a236de178ba1d5a5513",
          "sha1": "6110b37f38bb46d51c6d80e3e1de85a85b84da39",
          "md5": "a0c9a1500da483de749c02e97262ed29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.14.jar",
          "url": "megameklab-0.49.14.jar",
          "size": 1064720,
          "sha512": "6be128188d99cc62c2ef1db51b0f7371bf187d6a20333a4d35a9063a08e12f6161c666ec35301d0fbfb3cf8d9413d9067ff2a5eeb84460abc2ec3354becb0e24",
          "sha256": "b61f75633b9f6da0cbdb96d6f8a40432ec9d40b127d06a236de178ba1d5a5513",
          "sha1": "6110b37f38bb46d51c6d80e3e1de85a85b84da39",
          "md5": "a0c9a1500da483de749c02e97262ed29"
        }
      ]
    }
  ]
}
