{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15.jar",
          "url": "megamek-0.49.15.jar",
          "size": 8461432,
          "sha512": "33cb7e11f9971c55dcf7a72adadc47e31aaaef505781c3a469751d632e349c1acdce021d46aa8572469f4f8dc03dc0ffbcb347316bc6b6a0778ca0c36f8f0432",
          "sha256": "12e43e4bd919043e499c85f6f54bfd693d42318fb690a5610d1eab6ce285dec5",
          "sha1": "4998edd9286de41b415e02cc162006dcb1729819",
          "md5": "b6017177ecffc6e052bda3d57df50f43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15.jar",
          "url": "megamek-0.49.15.jar",
          "size": 8461432,
          "sha512": "33cb7e11f9971c55dcf7a72adadc47e31aaaef505781c3a469751d632e349c1acdce021d46aa8572469f4f8dc03dc0ffbcb347316bc6b6a0778ca0c36f8f0432",
          "sha256": "12e43e4bd919043e499c85f6f54bfd693d42318fb690a5610d1eab6ce285dec5",
          "sha1": "4998edd9286de41b415e02cc162006dcb1729819",
          "md5": "b6017177ecffc6e052bda3d57df50f43"
        }
      ]
    }
  ]
}
