{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15.jar",
          "url": "megamek-0.49.15.jar",
          "size": 8459840,
          "sha512": "7214b8ed4f0b339db06aa93b709b31c226afe4a0a881d4d07b7dcd244c00796e70b8f1ff2ba7783906b8220c3ccbde0d502cafadde040777476dd9b1ddb90288",
          "sha256": "6274e6c6194fd577e3da9718c22d9d85049603c9720d2ecc1426574869178336",
          "sha1": "c77224cbe58dd889fee82666f849b4494a6dde62",
          "md5": "b4ce419550732427f46de14e30d1eb65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15.jar",
          "url": "megamek-0.49.15.jar",
          "size": 8459840,
          "sha512": "7214b8ed4f0b339db06aa93b709b31c226afe4a0a881d4d07b7dcd244c00796e70b8f1ff2ba7783906b8220c3ccbde0d502cafadde040777476dd9b1ddb90288",
          "sha256": "6274e6c6194fd577e3da9718c22d9d85049603c9720d2ecc1426574869178336",
          "sha1": "c77224cbe58dd889fee82666f849b4494a6dde62",
          "md5": "b4ce419550732427f46de14e30d1eb65"
        }
      ]
    }
  ]
}
