{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057357,
          "sha512": "df38d725a0622d0e2def975c0866121d7e71b19ecb36b210513a2180d24a0d7bd83b1c253fe4109c3f840370ea3de67d549d70527f729ddea28a1bb326f26808",
          "sha256": "197b9e4f60d519b0ce9df1459b2311a20b90c87d466b7498fc9d4e09977463e7",
          "sha1": "08f302a22c4369d270c427f55983f68aba55de42",
          "md5": "7ed813fb5ee951a1dee70f6f4529f20c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057357,
          "sha512": "df38d725a0622d0e2def975c0866121d7e71b19ecb36b210513a2180d24a0d7bd83b1c253fe4109c3f840370ea3de67d549d70527f729ddea28a1bb326f26808",
          "sha256": "197b9e4f60d519b0ce9df1459b2311a20b90c87d466b7498fc9d4e09977463e7",
          "sha1": "08f302a22c4369d270c427f55983f68aba55de42",
          "md5": "7ed813fb5ee951a1dee70f6f4529f20c"
        }
      ]
    }
  ]
}
