{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057173,
          "sha512": "7955bd6c01d7ff789f49c3f3580f95c9dbe9b957f1a0471ddfaf8971fc9e76564a5d303270c063c919360094466146cafa62636f2a9fbbd38615cfc1f60aa6ec",
          "sha256": "3ba7923a9744d9f95dc9b9bccb65c2eae5a241b4739546b35da1ae5cf13c5c68",
          "sha1": "9753ddcd0405c7f5e20bdd19fe682da42dda7c50",
          "md5": "338fbc2a5c71218348a3c8b3518e0463"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057173,
          "sha512": "7955bd6c01d7ff789f49c3f3580f95c9dbe9b957f1a0471ddfaf8971fc9e76564a5d303270c063c919360094466146cafa62636f2a9fbbd38615cfc1f60aa6ec",
          "sha256": "3ba7923a9744d9f95dc9b9bccb65c2eae5a241b4739546b35da1ae5cf13c5c68",
          "sha1": "9753ddcd0405c7f5e20bdd19fe682da42dda7c50",
          "md5": "338fbc2a5c71218348a3c8b3518e0463"
        }
      ]
    }
  ]
}
