{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057345,
          "sha512": "ca849c9fe8359459d6f0dfc5717ebad18d4b814bd114a503ed82f075fd79d555efc0b0f0484c58cfe6e90812e5f6731007986ad3693d4db09a365d068fc6bdbb",
          "sha256": "a93468df66a733ff21eb39cbf0839bf0c5ee4837cab5b63c978bfa82159db606",
          "sha1": "0a3aa6a4f270d39688b254c4c16642142d5a9fd1",
          "md5": "d914eaba74c0596efe0863caf3c84489"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057345,
          "sha512": "ca849c9fe8359459d6f0dfc5717ebad18d4b814bd114a503ed82f075fd79d555efc0b0f0484c58cfe6e90812e5f6731007986ad3693d4db09a365d068fc6bdbb",
          "sha256": "a93468df66a733ff21eb39cbf0839bf0c5ee4837cab5b63c978bfa82159db606",
          "sha1": "0a3aa6a4f270d39688b254c4c16642142d5a9fd1",
          "md5": "d914eaba74c0596efe0863caf3c84489"
        }
      ]
    }
  ]
}
