{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057928,
          "sha512": "c9b86f9d8c682f2519763255ee8e1f930d0b141776a3664165363c525cb70f8800dcce294a229c5bdcc5d5919f33d255d0cb8a055aa20cb5b238260146fb9838",
          "sha256": "f9ce7f02e6bc0074a631a881b2916c4989a7af7ba9608b641523aa8388e835d1",
          "sha1": "a8ce696d81ded8c82cef1e1c42315530f5b28120",
          "md5": "a8ade84d5463625a39d42c61653aea1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1057928,
          "sha512": "c9b86f9d8c682f2519763255ee8e1f930d0b141776a3664165363c525cb70f8800dcce294a229c5bdcc5d5919f33d255d0cb8a055aa20cb5b238260146fb9838",
          "sha256": "f9ce7f02e6bc0074a631a881b2916c4989a7af7ba9608b641523aa8388e835d1",
          "sha1": "a8ce696d81ded8c82cef1e1c42315530f5b28120",
          "md5": "a8ade84d5463625a39d42c61653aea1f"
        }
      ]
    }
  ]
}
