{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1056227,
          "sha512": "588afc9f22235a9ca0b65a77a7406f72452864ca3848498094af545b5660c6b451d166bbe1aabcf872b121a384ef77b1f913a44d83913fe0e8c6cfcc7d22c9ed",
          "sha256": "03946e69bdebba8411dcdf7fec457a1f0faa3d9838016a3f68d935c5cb371c86",
          "sha1": "5c7e5ece37f7582b073892c4716802cd5f1af37e",
          "md5": "2da3ba7725c9577613af5e1bcd43e407"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.12-SNAPSHOT.jar",
          "url": "megameklab-0.49.12-SNAPSHOT.jar",
          "size": 1056227,
          "sha512": "588afc9f22235a9ca0b65a77a7406f72452864ca3848498094af545b5660c6b451d166bbe1aabcf872b121a384ef77b1f913a44d83913fe0e8c6cfcc7d22c9ed",
          "sha256": "03946e69bdebba8411dcdf7fec457a1f0faa3d9838016a3f68d935c5cb371c86",
          "sha1": "5c7e5ece37f7582b073892c4716802cd5f1af37e",
          "md5": "2da3ba7725c9577613af5e1bcd43e407"
        }
      ]
    }
  ]
}
