{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8714102,
          "sha512": "56b5451df3e0ffa273f04c9c5660623df5c0c72cfee8c570a49073d550a74245dd5080da4b6859ba6875feb5467b57c0f14e9eddb01d588c4026349e879e81b0",
          "sha256": "6b210d081f0e5c7312e77f7029ed09c640ab7164592b4c5e8a74f67845c9bbca",
          "sha1": "4376daddc8169fbbbee96e1d37260ab48cf3d628",
          "md5": "168ccde2a633000ef250f00e42991b7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8714102,
          "sha512": "56b5451df3e0ffa273f04c9c5660623df5c0c72cfee8c570a49073d550a74245dd5080da4b6859ba6875feb5467b57c0f14e9eddb01d588c4026349e879e81b0",
          "sha256": "6b210d081f0e5c7312e77f7029ed09c640ab7164592b4c5e8a74f67845c9bbca",
          "sha1": "4376daddc8169fbbbee96e1d37260ab48cf3d628",
          "md5": "168ccde2a633000ef250f00e42991b7d"
        }
      ]
    }
  ]
}
