{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8802299,
          "sha512": "a8629b3e2d701a58ee5609ec6f8494d97f455f90891ebb3a9b038e941e063cda49e5fac7a0ccc716ad7e690232cf5c069c5d4123b269b47dcbe84529aad17dfa",
          "sha256": "f91427e3ff163925d52d0c3817a0db91c86fb9cdc2170c29c40cd11446cb8c60",
          "sha1": "2c4f87f82ecd54cc4a3344fbb3b77a4c22dccd9c",
          "md5": "35998885593fc35ba3bbfdcc88a7de43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.32"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf-extras",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8802299,
          "sha512": "a8629b3e2d701a58ee5609ec6f8494d97f455f90891ebb3a9b038e941e063cda49e5fac7a0ccc716ad7e690232cf5c069c5d4123b269b47dcbe84529aad17dfa",
          "sha256": "f91427e3ff163925d52d0c3817a0db91c86fb9cdc2170c29c40cd11446cb8c60",
          "sha1": "2c4f87f82ecd54cc4a3344fbb3b77a4c22dccd9c",
          "md5": "35998885593fc35ba3bbfdcc88a7de43"
        }
      ]
    }
  ]
}
