{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8722739,
          "sha512": "ba8fd32ad226d4472dc882f055eae0b158495cb342150a75a58ba1d42a8daa502fdb348b3c4342205b50c65422b90101e3f7002c93d495aa4abf59e76f1f8822",
          "sha256": "19a7de9b0e7ddc6fbcd9d4d93f7650053612e2e26c081e172b0e452e3ebc2eab",
          "sha1": "bf371d10305d952ac4c4774a5e54bbc6a8d151a4",
          "md5": "7bf4ec7ff42b163093f869dfbd4e8e1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8722739,
          "sha512": "ba8fd32ad226d4472dc882f055eae0b158495cb342150a75a58ba1d42a8daa502fdb348b3c4342205b50c65422b90101e3f7002c93d495aa4abf59e76f1f8822",
          "sha256": "19a7de9b0e7ddc6fbcd9d4d93f7650053612e2e26c081e172b0e452e3ebc2eab",
          "sha1": "bf371d10305d952ac4c4774a5e54bbc6a8d151a4",
          "md5": "7bf4ec7ff42b163093f869dfbd4e8e1a"
        }
      ]
    }
  ]
}
