{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8752015,
          "sha512": "3a7c87577bf96dec1c38df04f98f286e6f252945d184dd49b091a588c78e45d3dfb2523af54ee8d423ffbac59e041f68f51cdda2aff7da29b53d6f3768aed95e",
          "sha256": "65c56af52c96883292c906cdf8be14e654d07413ce81bcf6d6abd9667c8d6128",
          "sha1": "7111bf238142c9ab6cdc530f7703a431b1b9068e",
          "md5": "e1de9fc791bca2e2efbad1af1d7c1b6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.32"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8752015,
          "sha512": "3a7c87577bf96dec1c38df04f98f286e6f252945d184dd49b091a588c78e45d3dfb2523af54ee8d423ffbac59e041f68f51cdda2aff7da29b53d6f3768aed95e",
          "sha256": "65c56af52c96883292c906cdf8be14e654d07413ce81bcf6d6abd9667c8d6128",
          "sha1": "7111bf238142c9ab6cdc530f7703a431b1b9068e",
          "md5": "e1de9fc791bca2e2efbad1af1d7c1b6f"
        }
      ]
    }
  ]
}
