{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8807780,
          "sha512": "2f24004ab11d8e75fd11ddcd9475c153635767501e0b5b045747a5550283c147d80ba814072667ff50b2594a319531953a7b734d170c0fdd1bb83a7912548353",
          "sha256": "200ed1372ca692bfd96ca75cbdafa81096d0bac2a9e0746c6ec9ff3b41fafa5e",
          "sha1": "512815874dd6399024cf5943a61f1d87154dcb2d",
          "md5": "ca6ab6dfb3119285e23e659ec33671ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.32"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf-extras",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20-SNAPSHOT.jar",
          "url": "megamek-0.49.20-SNAPSHOT.jar",
          "size": 8807780,
          "sha512": "2f24004ab11d8e75fd11ddcd9475c153635767501e0b5b045747a5550283c147d80ba814072667ff50b2594a319531953a7b734d170c0fdd1bb83a7912548353",
          "sha256": "200ed1372ca692bfd96ca75cbdafa81096d0bac2a9e0746c6ec9ff3b41fafa5e",
          "sha1": "512815874dd6399024cf5943a61f1d87154dcb2d",
          "md5": "ca6ab6dfb3119285e23e659ec33671ac"
        }
      ]
    }
  ]
}
