{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8623244,
          "sha512": "3eea2448700323a223b13043559f4422e033ecf650051bbc53a825564684fd2ad26fe7773cd9e94b01033341254aba9bb4a7a476810207d863ebd07bd4be8b1f",
          "sha256": "37f40c1b0c9dccc9c31249ea0607edffc5f0b53a04f33db9e459c86b634fbb80",
          "sha1": "5b59f30d9ac070c8edd1762987561d9c86199448",
          "md5": "d3df0d59b27b3c12e57dd5e24cbcfc5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8623244,
          "sha512": "3eea2448700323a223b13043559f4422e033ecf650051bbc53a825564684fd2ad26fe7773cd9e94b01033341254aba9bb4a7a476810207d863ebd07bd4be8b1f",
          "sha256": "37f40c1b0c9dccc9c31249ea0607edffc5f0b53a04f33db9e459c86b634fbb80",
          "sha1": "5b59f30d9ac070c8edd1762987561d9c86199448",
          "md5": "d3df0d59b27b3c12e57dd5e24cbcfc5d"
        }
      ]
    }
  ]
}
