{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8685132,
          "sha512": "a6e97a7c276476c0d9b4785b0b74ee031c7f0ffcee3626ee9882882ae6bd22fe9ff83634b09a6ea70391fe8f9f96fc5fd72405e56328a461709ca4c94a7d0a93",
          "sha256": "4fb1cfccdbb4a0d00002940f4054358281b9003c3ae308796a244df17f243985",
          "sha1": "647c4e63ab4a57151de769021f7704138686297c",
          "md5": "3b92d3a375200a082bb59862b83d2aa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8685132,
          "sha512": "a6e97a7c276476c0d9b4785b0b74ee031c7f0ffcee3626ee9882882ae6bd22fe9ff83634b09a6ea70391fe8f9f96fc5fd72405e56328a461709ca4c94a7d0a93",
          "sha256": "4fb1cfccdbb4a0d00002940f4054358281b9003c3ae308796a244df17f243985",
          "sha1": "647c4e63ab4a57151de769021f7704138686297c",
          "md5": "3b92d3a375200a082bb59862b83d2aa0"
        }
      ]
    }
  ]
}
