{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8622434,
          "sha512": "c52586edad45974646d89fb210ed9ae036f3aa64b49dde29f9225513fc7c902580366a21334c70d8137f83db40796d831cc541952f8a283a5fb0e97096e60c24",
          "sha256": "f9951214510db04ec8c7ef8b1974697db3d069714ac62f216c69b0398193586d",
          "sha1": "5491799c11bfab83130bf5543936c4e1c58101ee",
          "md5": "7e7186abe17d769e6f17955979a57d6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8622434,
          "sha512": "c52586edad45974646d89fb210ed9ae036f3aa64b49dde29f9225513fc7c902580366a21334c70d8137f83db40796d831cc541952f8a283a5fb0e97096e60c24",
          "sha256": "f9951214510db04ec8c7ef8b1974697db3d069714ac62f216c69b0398193586d",
          "sha1": "5491799c11bfab83130bf5543936c4e1c58101ee",
          "md5": "7e7186abe17d769e6f17955979a57d6b"
        }
      ]
    }
  ]
}
