{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8685899,
          "sha512": "b3912cabff5cb815e36a6264d6b03091468f6da6c6d263f304b0ead4c38efb10f222eb9c395746f1df9717dec64d5c0b8cfa3b6575e3f7a348052fecf8054ea0",
          "sha256": "d6b51ff61f6cc855189b2ec966305bbecd2a4218d49083ce64fc74827ab39527",
          "sha1": "f668617c0f0c01622063630cb941527c3c294549",
          "md5": "f58f810e040b2c7d5cc0a594cbead612"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8685899,
          "sha512": "b3912cabff5cb815e36a6264d6b03091468f6da6c6d263f304b0ead4c38efb10f222eb9c395746f1df9717dec64d5c0b8cfa3b6575e3f7a348052fecf8054ea0",
          "sha256": "d6b51ff61f6cc855189b2ec966305bbecd2a4218d49083ce64fc74827ab39527",
          "sha1": "f668617c0f0c01622063630cb941527c3c294549",
          "md5": "f58f810e040b2c7d5cc0a594cbead612"
        }
      ]
    }
  ]
}
