{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.19-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8622574,
          "sha512": "ab6bd27b5146f85be408b1cbba263541dfe0cb06f25034d5b50e0de61dd605c48b055dd35cd45f8c56427c4a22c4c72dd8d6067aa93ccbb202e7c361879a41a1",
          "sha256": "70e98a97dea91a125799c895915e73e10e2748477df21c944a3377ff4b99e2f9",
          "sha1": "27e3444f387c3322d3dc3e008d61205d4e03d0aa",
          "md5": "9ea98a74b94aa80eb308c7ed786bd7ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.19-SNAPSHOT.jar",
          "url": "megamek-0.49.19-SNAPSHOT.jar",
          "size": 8622574,
          "sha512": "ab6bd27b5146f85be408b1cbba263541dfe0cb06f25034d5b50e0de61dd605c48b055dd35cd45f8c56427c4a22c4c72dd8d6067aa93ccbb202e7c361879a41a1",
          "sha256": "70e98a97dea91a125799c895915e73e10e2748477df21c944a3377ff4b99e2f9",
          "sha1": "27e3444f387c3322d3dc3e008d61205d4e03d0aa",
          "md5": "9ea98a74b94aa80eb308c7ed786bd7ce"
        }
      ]
    }
  ]
}
