{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.12.jar",
          "url": "megameklab-0.49.12.jar",
          "size": 1056473,
          "sha512": "f64b781bbb9842edb11c99cf2288bdab9dd9d06fcd30040d4b303a944057cfa52dabaac4735530c7cc463f458f29fc122e167102180b10dd2727b8984419e2c6",
          "sha256": "4dc7d39d6dc6019dd7694b10edd7ba60303940c5b2a9fe14d97a40a5f1419b0c",
          "sha1": "50637eb7c500a22583429b6995503d76e93ff5de",
          "md5": "d12b1d4ffcbc8fb8aa221c5301095180"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.12.jar",
          "url": "megameklab-0.49.12.jar",
          "size": 1056473,
          "sha512": "f64b781bbb9842edb11c99cf2288bdab9dd9d06fcd30040d4b303a944057cfa52dabaac4735530c7cc463f458f29fc122e167102180b10dd2727b8984419e2c6",
          "sha256": "4dc7d39d6dc6019dd7694b10edd7ba60303940c5b2a9fe14d97a40a5f1419b0c",
          "sha1": "50637eb7c500a22583429b6995503d76e93ff5de",
          "md5": "d12b1d4ffcbc8fb8aa221c5301095180"
        }
      ]
    }
  ]
}
