{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "yzn5qj6huvhxjjm52cqwgvorkq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092238,
          "sha512": "fa0af6144be73749db74b80af02d7b4454be40104eb46ff591d7a7c0bf25c6795efc3244ae13d7641335880a7ea8b3bc9b36db5cd1aa20e80019657a80927f88",
          "sha256": "c5d8545d602ab2e6ce44536e627043fd478a57123ce1f7e102f5cacd40bce252",
          "sha1": "21c14d3bee8ae652325bd8cbf9d9e9c029414d35",
          "md5": "c974c9f3f28b8ce22939dfd9a174c234"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.24"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092238,
          "sha512": "fa0af6144be73749db74b80af02d7b4454be40104eb46ff591d7a7c0bf25c6795efc3244ae13d7641335880a7ea8b3bc9b36db5cd1aa20e80019657a80927f88",
          "sha256": "c5d8545d602ab2e6ce44536e627043fd478a57123ce1f7e102f5cacd40bce252",
          "sha1": "21c14d3bee8ae652325bd8cbf9d9e9c029414d35",
          "md5": "c974c9f3f28b8ce22939dfd9a174c234"
        }
      ]
    }
  ]
}
