{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wxldgpohzrdrrahat37jt2zuru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092236,
          "sha512": "d43da4bc4c641f5f7588eaec8b1deb27a10ad06f15ab77b2b4c09a6e11006c6885c444b53356fb763a482a99ca5dc98833d6cd4b82406140e3fbb055f100e862",
          "sha256": "da410260788ff349f14727401879324bde32c6cd0a9ae27bc35878e7072ecc95",
          "sha1": "cb76a243edfd433343e59536c19f9de964629dd3",
          "md5": "832bb66e218a8a1f8c0063a43deae3ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.24"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092236,
          "sha512": "d43da4bc4c641f5f7588eaec8b1deb27a10ad06f15ab77b2b4c09a6e11006c6885c444b53356fb763a482a99ca5dc98833d6cd4b82406140e3fbb055f100e862",
          "sha256": "da410260788ff349f14727401879324bde32c6cd0a9ae27bc35878e7072ecc95",
          "sha1": "cb76a243edfd433343e59536c19f9de964629dd3",
          "md5": "832bb66e218a8a1f8c0063a43deae3ea"
        }
      ]
    }
  ]
}
