{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "okkyczakjjao3da4t2e47iz7p4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092752,
          "sha512": "7852fac906a1fb1ec52a3c06554cfb8cc07fc04ec6b3f7fe92c37ebe7270be0f0d246be2c012169854fd719b8d495182373f10fe5bf3e03586c7a2e634b7271d",
          "sha256": "b81a404da429ae29ddc7870776d8fe2559ab6447b7780590dc86436c9e822dab",
          "sha1": "6c0aa5ab7977cf75557bf8450d35d6576e197728",
          "md5": "3907bc9371dabe8785cbfe01f8c60675"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.10"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.19"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092752,
          "sha512": "7852fac906a1fb1ec52a3c06554cfb8cc07fc04ec6b3f7fe92c37ebe7270be0f0d246be2c012169854fd719b8d495182373f10fe5bf3e03586c7a2e634b7271d",
          "sha256": "b81a404da429ae29ddc7870776d8fe2559ab6447b7780590dc86436c9e822dab",
          "sha1": "6c0aa5ab7977cf75557bf8450d35d6576e197728",
          "md5": "3907bc9371dabe8785cbfe01f8c60675"
        }
      ]
    }
  ]
}
