{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "mrtrhdeqbfdnpm6icsn4qhjtfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092224,
          "sha512": "cf472bece61c6ba2881bcf4d656b0e7333c31f25706d4d7e7c27244b5c8066d4d1199720abcf0ffd6d96919008c2c2b183b737b71a4f39c7ce836cbced55b0c2",
          "sha256": "9453bc51fb3924171586c7da6e68ae4ac92fc2652a11ed81541ccd733fd1613f",
          "sha1": "1ebd2225ebd4b0646a84ceebc2faf0214472f92c",
          "md5": "d8d8ce476122588f6c4804c8a42ad196"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.6-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.24"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.6-SNAPSHOT.jar",
          "url": "megameklab-0.49.6-SNAPSHOT.jar",
          "size": 1092224,
          "sha512": "cf472bece61c6ba2881bcf4d656b0e7333c31f25706d4d7e7c27244b5c8066d4d1199720abcf0ffd6d96919008c2c2b183b737b71a4f39c7ce836cbced55b0c2",
          "sha256": "9453bc51fb3924171586c7da6e68ae4ac92fc2652a11ed81541ccd733fd1613f",
          "sha1": "1ebd2225ebd4b0646a84ceebc2faf0214472f92c",
          "md5": "d8d8ce476122588f6c4804c8a42ad196"
        }
      ]
    }
  ]
}
