{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.10-SNAPSHOT.jar",
          "url": "megamek-0.49.10-SNAPSHOT.jar",
          "size": 7771565,
          "sha512": "efc5cb97c37e24df1d9dc2726b2295771a176c66f0098e80cdefa0d88bb05baba3a65000b6a06a57c62c98d3af331cf151f7644975c7797214f463ff2f80c9c8",
          "sha256": "4d62d8ab0d18fe26977fbe405720009099c72fdc4f375f06949b2061b2a4a01f",
          "sha1": "5463123ab2b78b138982cc019625865d118bd282",
          "md5": "95af5c53e5a2add7bc17a0eb5175f9ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.10-SNAPSHOT.jar",
          "url": "megamek-0.49.10-SNAPSHOT.jar",
          "size": 7771565,
          "sha512": "efc5cb97c37e24df1d9dc2726b2295771a176c66f0098e80cdefa0d88bb05baba3a65000b6a06a57c62c98d3af331cf151f7644975c7797214f463ff2f80c9c8",
          "sha256": "4d62d8ab0d18fe26977fbe405720009099c72fdc4f375f06949b2061b2a4a01f",
          "sha1": "5463123ab2b78b138982cc019625865d118bd282",
          "md5": "95af5c53e5a2add7bc17a0eb5175f9ee"
        }
      ]
    }
  ]
}
