{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.10-SNAPSHOT.jar",
          "url": "megamek-0.49.10-SNAPSHOT.jar",
          "size": 7771622,
          "sha512": "c35ce3170a4e1b331aafbd7781666fd67f56324e5b93c7143fdcd2cd9430566a6594b700ce1353a349ea583989c2876793744d67502c3a2919177927b6faa898",
          "sha256": "6a02c290ec7681a1433a05470f68c4bdbf236b47a99e749f05e8e93ba5f6f690",
          "sha1": "9d699d764b93678670b6ff7cf6f91805e00e2c40",
          "md5": "b2c55524c0bb14c711f6abbe9f237651"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.10-SNAPSHOT.jar",
          "url": "megamek-0.49.10-SNAPSHOT.jar",
          "size": 7771622,
          "sha512": "c35ce3170a4e1b331aafbd7781666fd67f56324e5b93c7143fdcd2cd9430566a6594b700ce1353a349ea583989c2876793744d67502c3a2919177927b6faa898",
          "sha256": "6a02c290ec7681a1433a05470f68c4bdbf236b47a99e749f05e8e93ba5f6f690",
          "sha1": "9d699d764b93678670b6ff7cf6f91805e00e2c40",
          "md5": "b2c55524c0bb14c711f6abbe9f237651"
        }
      ]
    }
  ]
}
