{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.10-SNAPSHOT.jar",
          "url": "megamek-0.49.10-SNAPSHOT.jar",
          "size": 7772978,
          "sha512": "7919f5e50544c0d2d868806ae94ffe7cc2f292c171363605f2e3cd849395c172d769fa2d89e274464ad54d3f145bdef795032b29a86289a97999a9c527ab8a15",
          "sha256": "c682455d5d3b8a2633e87c8d774a07ac209574e9b9cd2df5c389317e8ccbe93b",
          "sha1": "0315955b83f3ccb170f8f5f301bd9f0f86dda83f",
          "md5": "b32994d4e921ed7499b898ed511587ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.10-SNAPSHOT.jar",
          "url": "megamek-0.49.10-SNAPSHOT.jar",
          "size": 7772978,
          "sha512": "7919f5e50544c0d2d868806ae94ffe7cc2f292c171363605f2e3cd849395c172d769fa2d89e274464ad54d3f145bdef795032b29a86289a97999a9c527ab8a15",
          "sha256": "c682455d5d3b8a2633e87c8d774a07ac209574e9b9cd2df5c389317e8ccbe93b",
          "sha1": "0315955b83f3ccb170f8f5f301bd9f0f86dda83f",
          "md5": "b32994d4e921ed7499b898ed511587ae"
        }
      ]
    }
  ]
}
