{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045402,
          "sha512": "d61b471a2b1cfb1ef4f25876f806a4155a2719000d1ff7b3193169c78c49b23e2ab517b0684831cfa73790b422bc1fb1edb2afa0d13052829d6ba388f4332202",
          "sha256": "d84e62cfd3fcfb7832380d727c586fa33974b5efac0b140c27cf59746edeeba9",
          "sha1": "26c0cde9b688ebe209780f60bd21bb89e19dba51",
          "md5": "4c476a1cb9c6ce9c517ea9df13a32734"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.11-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045402,
          "sha512": "d61b471a2b1cfb1ef4f25876f806a4155a2719000d1ff7b3193169c78c49b23e2ab517b0684831cfa73790b422bc1fb1edb2afa0d13052829d6ba388f4332202",
          "sha256": "d84e62cfd3fcfb7832380d727c586fa33974b5efac0b140c27cf59746edeeba9",
          "sha1": "26c0cde9b688ebe209780f60bd21bb89e19dba51",
          "md5": "4c476a1cb9c6ce9c517ea9df13a32734"
        }
      ]
    }
  ]
}
