{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045421,
          "sha512": "78bd365cb0bda1a36fc984ad468ce0c7b81c2c12caac4bb0f8329feab0e35ea4f725f2f238da25b9dba4c504bea104fcdec8b75dafbc324d8332d9dfd776118f",
          "sha256": "9e058b64ee0fe819171acc17e7871408a912e6646041b74a7770c182e8643548",
          "sha1": "503267e50aa774764e627af3317d03f0745ff9b5",
          "md5": "e6bc4f0ff80bb7d56fec19f3c265a1fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.11-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045421,
          "sha512": "78bd365cb0bda1a36fc984ad468ce0c7b81c2c12caac4bb0f8329feab0e35ea4f725f2f238da25b9dba4c504bea104fcdec8b75dafbc324d8332d9dfd776118f",
          "sha256": "9e058b64ee0fe819171acc17e7871408a912e6646041b74a7770c182e8643548",
          "sha1": "503267e50aa774764e627af3317d03f0745ff9b5",
          "md5": "e6bc4f0ff80bb7d56fec19f3c265a1fb"
        }
      ]
    }
  ]
}
