{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045515,
          "sha512": "7c8cd5e152337935010778014d91a93ec703090608b256a2083e9d37471f95f05acfce6d85755b8f63d1163a618989015d8a12b2a8e8240f0a9660344aeb84ba",
          "sha256": "f8f3dde8cb0a61504e8da18f6484e4bb725e15f560fb19210f7bd56cd8e57d64",
          "sha1": "ab3bd12b3d7e4934b30c69c0c40c98928495f070",
          "md5": "2eab74f11458b91591de18fbc4bb51c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.11-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045515,
          "sha512": "7c8cd5e152337935010778014d91a93ec703090608b256a2083e9d37471f95f05acfce6d85755b8f63d1163a618989015d8a12b2a8e8240f0a9660344aeb84ba",
          "sha256": "f8f3dde8cb0a61504e8da18f6484e4bb725e15f560fb19210f7bd56cd8e57d64",
          "sha1": "ab3bd12b3d7e4934b30c69c0c40c98928495f070",
          "md5": "2eab74f11458b91591de18fbc4bb51c6"
        }
      ]
    }
  ]
}
