{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045578,
          "sha512": "bea2c5f8b092363ff9621f9d4804530d1fefea88ae4714677a5723356bed54b02ba441e9b210f0f1b8398c2e8328f085b2a24a01e92435c72c997038ece08f32",
          "sha256": "204fba5f5023ebf90012d46359500c0969efe31c11a9a33c38ee047cd8b4d62a",
          "sha1": "27b5c28770c94ffa991cc71d3b4ab3bc24da4460",
          "md5": "e3bad8ecc0b6431b600402a245ff09c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.11-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.11-SNAPSHOT.jar",
          "url": "megameklab-0.49.11-SNAPSHOT.jar",
          "size": 1045578,
          "sha512": "bea2c5f8b092363ff9621f9d4804530d1fefea88ae4714677a5723356bed54b02ba441e9b210f0f1b8398c2e8328f085b2a24a01e92435c72c997038ece08f32",
          "sha256": "204fba5f5023ebf90012d46359500c0969efe31c11a9a33c38ee047cd8b4d62a",
          "sha1": "27b5c28770c94ffa991cc71d3b4ab3bc24da4460",
          "md5": "e3bad8ecc0b6431b600402a245ff09c6"
        }
      ]
    }
  ]
}
