{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8463574,
          "sha512": "35df1c3b68e5b884ba9ef8ae7c71bf6b3ce47d617661040cdfc69c43c9ba18b9a7f3876ab69edc63b8892168c05be30dc11b46a0bd90234e520b4bd4525e70d6",
          "sha256": "d8e1d548fca4151d09602d1990bc1808815930fe3ab9daef4b8bc74d28dc8f9e",
          "sha1": "8ef8e3640ec380e1c6d6ecb3ba38ad73dadf7147",
          "md5": "35679842a29c0ef61933e3457c90f0a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8463574,
          "sha512": "35df1c3b68e5b884ba9ef8ae7c71bf6b3ce47d617661040cdfc69c43c9ba18b9a7f3876ab69edc63b8892168c05be30dc11b46a0bd90234e520b4bd4525e70d6",
          "sha256": "d8e1d548fca4151d09602d1990bc1808815930fe3ab9daef4b8bc74d28dc8f9e",
          "sha1": "8ef8e3640ec380e1c6d6ecb3ba38ad73dadf7147",
          "md5": "35679842a29c0ef61933e3457c90f0a0"
        }
      ]
    }
  ]
}
