{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8432949,
          "sha512": "a23b88ecd0e11563b8407b6da3ba7db735d39028e05f24e0a41e22d17d9f7ad6f70726f2110bc7baa97efbf7f6826eb8e8b863d30609c7bf6772075d3be0fe96",
          "sha256": "6ae972eb9640fcbc3f6a4225afd428bd3b71be6e8cc8b86845e8b41811c5d13c",
          "sha1": "75f6d5f2c735e069e7e395e72d4514b2f0e96f27",
          "md5": "fc865f09a29068f9394bb751ff5df59f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8432949,
          "sha512": "a23b88ecd0e11563b8407b6da3ba7db735d39028e05f24e0a41e22d17d9f7ad6f70726f2110bc7baa97efbf7f6826eb8e8b863d30609c7bf6772075d3be0fe96",
          "sha256": "6ae972eb9640fcbc3f6a4225afd428bd3b71be6e8cc8b86845e8b41811c5d13c",
          "sha1": "75f6d5f2c735e069e7e395e72d4514b2f0e96f27",
          "md5": "fc865f09a29068f9394bb751ff5df59f"
        }
      ]
    }
  ]
}
