{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8432952,
          "sha512": "5163530eaa30cfcce6483b6a183221859e79c932496319d4624c7a19ab0c9e75ce81dad854eb721315cf65dc6f4658021b8e49b70559379be5f37af2c3e7d8c3",
          "sha256": "cd74b235143540894a9e5cd90bcb917c68871fce80dd297a3c1c0f78153b1360",
          "sha1": "85cb96b730031bfeb4c625db64bf86ba6929cb14",
          "md5": "52fb98bfa0a9b7f0a1888672ed06f059"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8432952,
          "sha512": "5163530eaa30cfcce6483b6a183221859e79c932496319d4624c7a19ab0c9e75ce81dad854eb721315cf65dc6f4658021b8e49b70559379be5f37af2c3e7d8c3",
          "sha256": "cd74b235143540894a9e5cd90bcb917c68871fce80dd297a3c1c0f78153b1360",
          "sha1": "85cb96b730031bfeb4c625db64bf86ba6929cb14",
          "md5": "52fb98bfa0a9b7f0a1888672ed06f059"
        }
      ]
    }
  ]
}
