{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8432951,
          "sha512": "515374f091538757cad6865fb06ded0c24e32bbc372a011916d10ed7fb60f8fb7cb5b61f7d0525ecc117e0f13657a5f15be2367d46465d1f3e28753c5d1d0c98",
          "sha256": "50be6a3227b6106183beb3717de7d6905884382b093f7582d6882466fd3823d0",
          "sha1": "22d5b4ecae7eafe520251ac21d3711c1795e17d1",
          "md5": "75ef66c491369445409c2e2f699598a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8432951,
          "sha512": "515374f091538757cad6865fb06ded0c24e32bbc372a011916d10ed7fb60f8fb7cb5b61f7d0525ecc117e0f13657a5f15be2367d46465d1f3e28753c5d1d0c98",
          "sha256": "50be6a3227b6106183beb3717de7d6905884382b093f7582d6882466fd3823d0",
          "sha1": "22d5b4ecae7eafe520251ac21d3711c1795e17d1",
          "md5": "75ef66c491369445409c2e2f699598a7"
        }
      ]
    }
  ]
}
