{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8453432,
          "sha512": "e9957e71946dd2dc6f896ded99f4c0b45bc71376ed4b50bd59841e3e14c948c7d97f2b795eb411450e91fa2bd2920f02aa5cc6a67833f8f3a85e3fbd20f4edcc",
          "sha256": "e286ffc832329fe065158b675cb76a84ad3f2662a35ce21f82ad90559a7cd2ff",
          "sha1": "cbbba2d2fc60f2f44fa18c24a85987a3dee6a6f8",
          "md5": "c26aaff3d3b194d90410e2be65fe76ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.14-SNAPSHOT.jar",
          "url": "megamek-0.49.14-SNAPSHOT.jar",
          "size": 8453432,
          "sha512": "e9957e71946dd2dc6f896ded99f4c0b45bc71376ed4b50bd59841e3e14c948c7d97f2b795eb411450e91fa2bd2920f02aa5cc6a67833f8f3a85e3fbd20f4edcc",
          "sha256": "e286ffc832329fe065158b675cb76a84ad3f2662a35ce21f82ad90559a7cd2ff",
          "sha1": "cbbba2d2fc60f2f44fa18c24a85987a3dee6a6f8",
          "md5": "c26aaff3d3b194d90410e2be65fe76ea"
        }
      ]
    }
  ]
}
