{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.11-SNAPSHOT.jar",
          "url": "mekhq-0.49.11-SNAPSHOT.jar",
          "size": 3892704,
          "sha512": "bd26c6866858986d3df4487e03826c39cf8db2b644bc59f22a9e792cc91e586c946ef2857c70178a687f0c37f463c814c0dda98db760f4cb272accc3db1ab790",
          "sha256": "5b34ff6ac450f2aab9598b2cff9828663f040ed7a382b6fc64622d4e906dd667",
          "sha1": "43c8bca5d4b1a6a640515fca8c8f4a0a4b27f0f6",
          "md5": "a094b993c53799a76317ecdc9e3605d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.11-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.11-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.11-SNAPSHOT.jar",
          "url": "mekhq-0.49.11-SNAPSHOT.jar",
          "size": 3892704,
          "sha512": "bd26c6866858986d3df4487e03826c39cf8db2b644bc59f22a9e792cc91e586c946ef2857c70178a687f0c37f463c814c0dda98db760f4cb272accc3db1ab790",
          "sha256": "5b34ff6ac450f2aab9598b2cff9828663f040ed7a382b6fc64622d4e906dd667",
          "sha1": "43c8bca5d4b1a6a640515fca8c8f4a0a4b27f0f6",
          "md5": "a094b993c53799a76317ecdc9e3605d9"
        }
      ]
    }
  ]
}
