{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.10.jar",
          "url": "megamek-0.49.10.jar",
          "size": 7771558,
          "sha512": "0f735de60be1e9d5a085ae87531896dac5f193567e0a7ecf28ede39b738e869469ec69c1828fa083be140586f435f8b42d2253a995750d032041d5973331da6a",
          "sha256": "493be31d480894430fefa4566110dd4d886a15841ef6064e072e877847b48a59",
          "sha1": "cae7880e3ddcb309fa7d319577aa228ceeacc3ac",
          "md5": "de6ecaaf5d8730fd36a93e1ed68579ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.10.jar",
          "url": "megamek-0.49.10.jar",
          "size": 7771558,
          "sha512": "0f735de60be1e9d5a085ae87531896dac5f193567e0a7ecf28ede39b738e869469ec69c1828fa083be140586f435f8b42d2253a995750d032041d5973331da6a",
          "sha256": "493be31d480894430fefa4566110dd4d886a15841ef6064e072e877847b48a59",
          "sha1": "cae7880e3ddcb309fa7d319577aa228ceeacc3ac",
          "md5": "de6ecaaf5d8730fd36a93e1ed68579ae"
        }
      ]
    }
  ]
}
