{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.10.jar",
          "url": "megamek-0.49.10.jar",
          "size": 7773068,
          "sha512": "e0ea2939045139b01e4539a908ec1c74936af8663cfbd5f80cb3494e1552973e6cf98a4c57e8fdd571aabb1a0e31c05f39ce6f476ccad5feb10c05a8ba628893",
          "sha256": "e1315563f92b3b92c6cb204594dece08b603f9b80982d3831734ccd6ffd381cd",
          "sha1": "69bb16b1646f1f521777e36e2b38af4e1954daf9",
          "md5": "9e8fcab7f63f96c630faa0e31618fe41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.10.jar",
          "url": "megamek-0.49.10.jar",
          "size": 7773068,
          "sha512": "e0ea2939045139b01e4539a908ec1c74936af8663cfbd5f80cb3494e1552973e6cf98a4c57e8fdd571aabb1a0e31c05f39ce6f476ccad5feb10c05a8ba628893",
          "sha256": "e1315563f92b3b92c6cb204594dece08b603f9b80982d3831734ccd6ffd381cd",
          "sha1": "69bb16b1646f1f521777e36e2b38af4e1954daf9",
          "md5": "9e8fcab7f63f96c630faa0e31618fe41"
        }
      ]
    }
  ]
}
