{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8012885,
          "sha512": "ceeb2e408e2816175abe7a30e497ad2858978abe0806c2395af050df26d113dc3867bc8470b303ecf6462b53f59b2e12805ccc9fa28d8c823498f7a5b1ee4439",
          "sha256": "be50ac10f8e234f33ca28e1d57a195971cb134b5a61005f400079603ea6d0d65",
          "sha1": "c546c4ed6183abaadbeadfbde07e01249d547773",
          "md5": "654df03c52a52e65f007a67b3fbdc00b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8012885,
          "sha512": "ceeb2e408e2816175abe7a30e497ad2858978abe0806c2395af050df26d113dc3867bc8470b303ecf6462b53f59b2e12805ccc9fa28d8c823498f7a5b1ee4439",
          "sha256": "be50ac10f8e234f33ca28e1d57a195971cb134b5a61005f400079603ea6d0d65",
          "sha1": "c546c4ed6183abaadbeadfbde07e01249d547773",
          "md5": "654df03c52a52e65f007a67b3fbdc00b"
        }
      ]
    }
  ]
}
