{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8006846,
          "sha512": "017e6e5858f307305921cccbdb381c1fe850070e9afadefb27e18589bd3a9abb2684d766fae4028e1c181da4a153176911e71e352368c99ed7b697cf9d0a0222",
          "sha256": "f9cd8b2f37ca283ffdfaef7a161e6c202ae2e6cbe8c4e9e883f00cc54429f68a",
          "sha1": "737254ca160ef700fc016b70ca71e98a0151fc72",
          "md5": "56913340876b412d69862120ac100e45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8006846,
          "sha512": "017e6e5858f307305921cccbdb381c1fe850070e9afadefb27e18589bd3a9abb2684d766fae4028e1c181da4a153176911e71e352368c99ed7b697cf9d0a0222",
          "sha256": "f9cd8b2f37ca283ffdfaef7a161e6c202ae2e6cbe8c4e9e883f00cc54429f68a",
          "sha1": "737254ca160ef700fc016b70ca71e98a0151fc72",
          "md5": "56913340876b412d69862120ac100e45"
        }
      ]
    }
  ]
}
