{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8002762,
          "sha512": "7fb8f355e8af730c0d053c7718649d7e9d1603c85a3494069f1e2fa5ed325fd3afcfa7b19c3b611e875b97ba68528b5bf3016106d5a7b02c7e1a82a2c1ebbedc",
          "sha256": "20e092cdf2bc68d13ec12ddf04338746099936c1f8b00f5f8006d5198bfd0277",
          "sha1": "d5cc9f7007e3282810364188baf451de48802f47",
          "md5": "6916f19a2b902228942019a10ff11d09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8002762,
          "sha512": "7fb8f355e8af730c0d053c7718649d7e9d1603c85a3494069f1e2fa5ed325fd3afcfa7b19c3b611e875b97ba68528b5bf3016106d5a7b02c7e1a82a2c1ebbedc",
          "sha256": "20e092cdf2bc68d13ec12ddf04338746099936c1f8b00f5f8006d5198bfd0277",
          "sha1": "d5cc9f7007e3282810364188baf451de48802f47",
          "md5": "6916f19a2b902228942019a10ff11d09"
        }
      ]
    }
  ]
}
