{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8032719,
          "sha512": "ee7587886d9205377f6de49490b92a48c321ec7e894505c81ad9940f6526345e04fb84a5d13aa8b076c48ddd0a5cc952e4f131ed53d622904ac1dffeb81b6e36",
          "sha256": "61151a327660675cfb0280d597433bc10d8534e9f14f19f1921dbbc4ccea0690",
          "sha1": "85d4c4803213d8bf8301ac2f3c79c74ae18e8718",
          "md5": "5894515d455e808b0cfacc221d7f6d7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8032719,
          "sha512": "ee7587886d9205377f6de49490b92a48c321ec7e894505c81ad9940f6526345e04fb84a5d13aa8b076c48ddd0a5cc952e4f131ed53d622904ac1dffeb81b6e36",
          "sha256": "61151a327660675cfb0280d597433bc10d8534e9f14f19f1921dbbc4ccea0690",
          "sha1": "85d4c4803213d8bf8301ac2f3c79c74ae18e8718",
          "md5": "5894515d455e808b0cfacc221d7f6d7a"
        }
      ]
    }
  ]
}
