{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8048980,
          "sha512": "1a95bd41ac6bd976c7ab5728a4d51b5928cc1102473b4a8c81e2780f15a6383e3c786269ac273cc3fc4e0dc98f85cf5de44e9c7e488f81d857ffdf4637388cb3",
          "sha256": "082651532e77c91bbfe62b0eb027a761714c3cd41628baf6e5a3db3fd88d1c3c",
          "sha1": "81a68b1e536415aa5cfe970baae55f31aa723e9d",
          "md5": "b2ae9b7eb6ea88376e87f3058abcbc87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.11-SNAPSHOT.jar",
          "url": "megamek-0.49.11-SNAPSHOT.jar",
          "size": 8048980,
          "sha512": "1a95bd41ac6bd976c7ab5728a4d51b5928cc1102473b4a8c81e2780f15a6383e3c786269ac273cc3fc4e0dc98f85cf5de44e9c7e488f81d857ffdf4637388cb3",
          "sha256": "082651532e77c91bbfe62b0eb027a761714c3cd41628baf6e5a3db3fd88d1c3c",
          "sha1": "81a68b1e536415aa5cfe970baae55f31aa723e9d",
          "md5": "b2ae9b7eb6ea88376e87f3058abcbc87"
        }
      ]
    }
  ]
}
