{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.50.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.50.0-SNAPSHOT.jar",
          "url": "mekhq-0.50.0-SNAPSHOT.jar",
          "size": 4404423,
          "sha512": "b0f15b7cbb0e4b04ce9be48d9246d82b5297490003c7b2eeff424f8c0a435007092200f92ff9a07d4d29276dc488c09e6fd5d2cd8f3312dcffaa0392a611f268",
          "sha256": "53b3b06e574d9574e2f5f92c6b042a296c66dc35b9f55323de95de152b6412e8",
          "sha1": "fc8bcc06b36b8a5a83997008e53274e2239b2e46",
          "md5": "0989fd76b64c79ed2b4446d3d02bf40b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.50.0-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.50.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.50.0-SNAPSHOT.jar",
          "url": "mekhq-0.50.0-SNAPSHOT.jar",
          "size": 4404423,
          "sha512": "b0f15b7cbb0e4b04ce9be48d9246d82b5297490003c7b2eeff424f8c0a435007092200f92ff9a07d4d29276dc488c09e6fd5d2cd8f3312dcffaa0392a611f268",
          "sha256": "53b3b06e574d9574e2f5f92c6b042a296c66dc35b9f55323de95de152b6412e8",
          "sha1": "fc8bcc06b36b8a5a83997008e53274e2239b2e46",
          "md5": "0989fd76b64c79ed2b4446d3d02bf40b"
        }
      ]
    }
  ]
}
