{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8425900,
          "sha512": "3f9818c73ccb3995fd1a78f02c3c2f9d179af74b359de7e7df101a33a78b8ecc4cb4d919912b8a25124fdf469a1caf568489fa27ce3575b54f670a9f9657d3e2",
          "sha256": "a8868f9cfb28bafed8d347b962dce76fb748c2459907765a2d3f74902dc3ff49",
          "sha1": "dbe344b3db60be212417db42cc6ae48a7d06a948",
          "md5": "8221a6c5677027045065fbbdf0a1809f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8425900,
          "sha512": "3f9818c73ccb3995fd1a78f02c3c2f9d179af74b359de7e7df101a33a78b8ecc4cb4d919912b8a25124fdf469a1caf568489fa27ce3575b54f670a9f9657d3e2",
          "sha256": "a8868f9cfb28bafed8d347b962dce76fb748c2459907765a2d3f74902dc3ff49",
          "sha1": "dbe344b3db60be212417db42cc6ae48a7d06a948",
          "md5": "8221a6c5677027045065fbbdf0a1809f"
        }
      ]
    }
  ]
}
