{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8445967,
          "sha512": "39697f5c68eeb04cd4ca906ed75ea4f735bf875b479cd6001f91f13de3fec8cd84d65f29f150a4db5b213860dd571589d39c9b6d51b7a266d81b2362f2a0e22f",
          "sha256": "0e1c7010a1cc9b76473cb1404dbce1527b9ea69cb1472d3fb2c5064a90d087e4",
          "sha1": "92b893f01cae03d06d80d70a2bea79eb7d00c33f",
          "md5": "7d3ec331ec5da0327913827917b30671"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8445967,
          "sha512": "39697f5c68eeb04cd4ca906ed75ea4f735bf875b479cd6001f91f13de3fec8cd84d65f29f150a4db5b213860dd571589d39c9b6d51b7a266d81b2362f2a0e22f",
          "sha256": "0e1c7010a1cc9b76473cb1404dbce1527b9ea69cb1472d3fb2c5064a90d087e4",
          "sha1": "92b893f01cae03d06d80d70a2bea79eb7d00c33f",
          "md5": "7d3ec331ec5da0327913827917b30671"
        }
      ]
    }
  ]
}
