{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8504834,
          "sha512": "403eefa81197bbceb1a9c866e7bd6b95ba3ed298b32f0e1c3bab105dfd2aae9cdc98aee177a7bb876bb442e79f0f50e19109c8c996dd130875b49d72c7861532",
          "sha256": "2b2e17e310df7f1f279c00b9f81ac69a7720cb395ef19287447d85230b17eeb9",
          "sha1": "14f5fb6a5af9e2a669c15557790f3de2b788d9d2",
          "md5": "98226999b8d2b9d6041f4e462d73e557"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8504834,
          "sha512": "403eefa81197bbceb1a9c866e7bd6b95ba3ed298b32f0e1c3bab105dfd2aae9cdc98aee177a7bb876bb442e79f0f50e19109c8c996dd130875b49d72c7861532",
          "sha256": "2b2e17e310df7f1f279c00b9f81ac69a7720cb395ef19287447d85230b17eeb9",
          "sha1": "14f5fb6a5af9e2a669c15557790f3de2b788d9d2",
          "md5": "98226999b8d2b9d6041f4e462d73e557"
        }
      ]
    }
  ]
}
