{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8497980,
          "sha512": "39ed3eb197aba1b95fd31cff029d768cf79faa8a6c45f9852790027faeca2d619bc40aaccb489d5d5b95e45eac5e71e7e56064a541b7ab2fb6ff190040897c0a",
          "sha256": "c15c5b2fb9c41e231e8d4b09ed9958b150da4c723325cc099e09f5b53e96583f",
          "sha1": "a3bcebf4591a6202855f31683c8b28bb26fc028d",
          "md5": "51ca9becdcc09bdc61caa3a10a961d3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8497980,
          "sha512": "39ed3eb197aba1b95fd31cff029d768cf79faa8a6c45f9852790027faeca2d619bc40aaccb489d5d5b95e45eac5e71e7e56064a541b7ab2fb6ff190040897c0a",
          "sha256": "c15c5b2fb9c41e231e8d4b09ed9958b150da4c723325cc099e09f5b53e96583f",
          "sha1": "a3bcebf4591a6202855f31683c8b28bb26fc028d",
          "md5": "51ca9becdcc09bdc61caa3a10a961d3c"
        }
      ]
    }
  ]
}
