{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.15-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8426163,
          "sha512": "4292b6ac3f4c7fb055e03729f5f8629cecf041aebd71b249d52709fc5164cefccfc24a4a199a44d01d20632338ea506db7dad7b67757f8e26027918f5c3dc6ba",
          "sha256": "2e5230b7b6ceddd25ae8ac7ece3ffa3ff4737cac875ed9e84ccb1b4fed12b087",
          "sha1": "6b20b21e1c974af06728106b425f59de760909b6",
          "md5": "135c9d6e17061b580e7d51eb5c4a78d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.15-SNAPSHOT.jar",
          "url": "megamek-0.49.15-SNAPSHOT.jar",
          "size": 8426163,
          "sha512": "4292b6ac3f4c7fb055e03729f5f8629cecf041aebd71b249d52709fc5164cefccfc24a4a199a44d01d20632338ea506db7dad7b67757f8e26027918f5c3dc6ba",
          "sha256": "2e5230b7b6ceddd25ae8ac7ece3ffa3ff4737cac875ed9e84ccb1b4fed12b087",
          "sha1": "6b20b21e1c974af06728106b425f59de760909b6",
          "md5": "135c9d6e17061b580e7d51eb5c4a78d4"
        }
      ]
    }
  ]
}
