{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8482787,
          "sha512": "742c8f0f4388bda0d0aa49d2c8b6bbd36cea2da101162b698f5c1b44b19b52e031782eeeac88e6587f783f565afd04b44b49ea022261d7f57464aadefe5f6953",
          "sha256": "5e0c939db61d0677e8cc1f252053cbf659f0a31acf8a0fbd53d64655fa2233c6",
          "sha1": "887c0e8dcca86314049bde5172cbba5ed5fa281a",
          "md5": "11c0f501dcd3a883de85ba689b8ae239"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8482787,
          "sha512": "742c8f0f4388bda0d0aa49d2c8b6bbd36cea2da101162b698f5c1b44b19b52e031782eeeac88e6587f783f565afd04b44b49ea022261d7f57464aadefe5f6953",
          "sha256": "5e0c939db61d0677e8cc1f252053cbf659f0a31acf8a0fbd53d64655fa2233c6",
          "sha1": "887c0e8dcca86314049bde5172cbba5ed5fa281a",
          "md5": "11c0f501dcd3a883de85ba689b8ae239"
        }
      ]
    }
  ]
}
