{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8476957,
          "sha512": "ae8150828e669ab22da602eda47aba279f892ef280de6ff88e8f33ab19610bfd06105a93c2f5eeeca6586dfc8134864da4b601bca718b4e646cd68be8fd92fea",
          "sha256": "a6d05209f1c52f3e6fd9131cb478804cf59b5142418583dcb52627193a6555d9",
          "sha1": "24d0a366b0d1bba7c821cb251778c8e813bd891e",
          "md5": "e14217a67a8be3289f329ac393adbb4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8476957,
          "sha512": "ae8150828e669ab22da602eda47aba279f892ef280de6ff88e8f33ab19610bfd06105a93c2f5eeeca6586dfc8134864da4b601bca718b4e646cd68be8fd92fea",
          "sha256": "a6d05209f1c52f3e6fd9131cb478804cf59b5142418583dcb52627193a6555d9",
          "sha1": "24d0a366b0d1bba7c821cb251778c8e813bd891e",
          "md5": "e14217a67a8be3289f329ac393adbb4c"
        }
      ]
    }
  ]
}
