{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8459937,
          "sha512": "8558d7831225d99c7b2ee7ff08895a2bea56595da37121e9f15287a581654b449fd4036ca001dc799af5f329cfd1b6351ee9d911c0b62997232dbb953977c2da",
          "sha256": "e4e51c3cec508e22c851c5fc9cbfd2ecdd7902abdbd3ed83e99e9515e79f1dab",
          "sha1": "db076ee9389c5b03f9baa873e239228cac869637",
          "md5": "616457a8a1544929a0dbdd8ed01949c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8459937,
          "sha512": "8558d7831225d99c7b2ee7ff08895a2bea56595da37121e9f15287a581654b449fd4036ca001dc799af5f329cfd1b6351ee9d911c0b62997232dbb953977c2da",
          "sha256": "e4e51c3cec508e22c851c5fc9cbfd2ecdd7902abdbd3ed83e99e9515e79f1dab",
          "sha1": "db076ee9389c5b03f9baa873e239228cac869637",
          "md5": "616457a8a1544929a0dbdd8ed01949c5"
        }
      ]
    }
  ]
}
