{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8474475,
          "sha512": "62d88fff4a461f39c711bb2dfed0b3a203c9123cf1d650c7e14102c5f340758264ede996c20be5ab66477f8138e11f62d2506a2fdb09c6afeb6f53b53712cc68",
          "sha256": "1777c7c976df029129c93d53a8f5c872ebf21b8e0949666ed0cbb9a9c53f4759",
          "sha1": "31f6d9de4f6dd963a732bd66a91e3781c5b67b7f",
          "md5": "d0b32ed666cd4d5e57e269f2093467a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16-SNAPSHOT.jar",
          "url": "megamek-0.49.16-SNAPSHOT.jar",
          "size": 8474475,
          "sha512": "62d88fff4a461f39c711bb2dfed0b3a203c9123cf1d650c7e14102c5f340758264ede996c20be5ab66477f8138e11f62d2506a2fdb09c6afeb6f53b53712cc68",
          "sha256": "1777c7c976df029129c93d53a8f5c872ebf21b8e0949666ed0cbb9a9c53f4759",
          "sha1": "31f6d9de4f6dd963a732bd66a91e3781c5b67b7f",
          "md5": "d0b32ed666cd4d5e57e269f2093467a0"
        }
      ]
    }
  ]
}
