{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.16-SNAPSHOT.jar",
          "url": "megameklab-0.49.16-SNAPSHOT.jar",
          "size": 1065643,
          "sha512": "06bf0c56305a3b69505e339484e99f9c6210fd7b6adc818a317de57eacd0c1e45f6acc9493afcd9a92c33cb735627e427f8b5db8d6aa0335760339b6cb7e5508",
          "sha256": "d3c3e314485a3a9cbb5c44cae3bae4d42ea05cf3ae3647a29f508113dcfb7a89",
          "sha1": "16082bdfc26b1277766a8be7fe0d0624f1d4ae5b",
          "md5": "2ec105066ba4e3ab04c17cd6d7205e46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.16-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.16-SNAPSHOT.jar",
          "url": "megameklab-0.49.16-SNAPSHOT.jar",
          "size": 1065643,
          "sha512": "06bf0c56305a3b69505e339484e99f9c6210fd7b6adc818a317de57eacd0c1e45f6acc9493afcd9a92c33cb735627e427f8b5db8d6aa0335760339b6cb7e5508",
          "sha256": "d3c3e314485a3a9cbb5c44cae3bae4d42ea05cf3ae3647a29f508113dcfb7a89",
          "sha1": "16082bdfc26b1277766a8be7fe0d0624f1d4ae5b",
          "md5": "2ec105066ba4e3ab04c17cd6d7205e46"
        }
      ]
    }
  ]
}
