{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "jpk6hj52gfhnngywsfoej6u7lm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.8-SNAPSHOT.jar",
          "url": "megameklab-0.49.8-SNAPSHOT.jar",
          "size": 1071339,
          "sha512": "de285dc6d371f366112f917e23ad3992d0fdcd159938c49d960fdde2ba0d0b1e0883b6d0fef8d7635aa9f37bcd3c56b5cf0fb8a8c5cdffc9e3bee653c7284abc",
          "sha256": "10f241ebf9a893aca93c82670af3ca1b95923b1e11d4f1c6d82da6213f9762d3",
          "sha1": "6ac633055230ba54b0eedf2e6e00b58040c404bf",
          "md5": "798e6e18182f20e29f91525fb6a0b8fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.8-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.24"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.8-SNAPSHOT.jar",
          "url": "megameklab-0.49.8-SNAPSHOT.jar",
          "size": 1071339,
          "sha512": "de285dc6d371f366112f917e23ad3992d0fdcd159938c49d960fdde2ba0d0b1e0883b6d0fef8d7635aa9f37bcd3c56b5cf0fb8a8c5cdffc9e3bee653c7284abc",
          "sha256": "10f241ebf9a893aca93c82670af3ca1b95923b1e11d4f1c6d82da6213f9762d3",
          "sha1": "6ac633055230ba54b0eedf2e6e00b58040c404bf",
          "md5": "798e6e18182f20e29f91525fb6a0b8fa"
        }
      ]
    }
  ]
}
