{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "qr3gh33qkjertp5fk7gjsbpdje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.8-SNAPSHOT.jar",
          "url": "megameklab-0.49.8-SNAPSHOT.jar",
          "size": 1078222,
          "sha512": "a17caff48cddd57cec8aefaa784c02e03230c0b489b671edcc8df7a820167f7633e9de81f829890db65e45879d90972cffbafeac185d00c8e54837a6f031d3a9",
          "sha256": "dceef03d208ba304da39ef742bfcbda29fd00fcb3e33f340dcad1bf61589fd8f",
          "sha1": "8eeab839a59438a8f2d6a372e219588d577946ef",
          "md5": "c27639db17bd7a5456ca4e2275d42a56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.8-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.25"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.8-SNAPSHOT.jar",
          "url": "megameklab-0.49.8-SNAPSHOT.jar",
          "size": 1078222,
          "sha512": "a17caff48cddd57cec8aefaa784c02e03230c0b489b671edcc8df7a820167f7633e9de81f829890db65e45879d90972cffbafeac185d00c8e54837a6f031d3a9",
          "sha256": "dceef03d208ba304da39ef742bfcbda29fd00fcb3e33f340dcad1bf61589fd8f",
          "sha1": "8eeab839a59438a8f2d6a372e219588d577946ef",
          "md5": "c27639db17bd7a5456ca4e2275d42a56"
        }
      ]
    }
  ]
}
