{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5zopm7x6f5db3d3hq5ckwfggle"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.8-SNAPSHOT.jar",
          "url": "megameklab-0.49.8-SNAPSHOT.jar",
          "size": 1042789,
          "sha512": "ed86edfe5f065771dc77781816a0dc81a3933a1e1d4d7eeada732581df104750ba1e5c32bbbf866e0cdcda20b5273608be84dafee2ea0c00b5ad93c772b40c21",
          "sha256": "c1c95a31370f18634f3ed7619fa0dc3832d2f1daefaefcaddeb6bf0030524841",
          "sha1": "e4c754149fbec1d961fc67e5070e7dc53f77d1cf",
          "md5": "f59cd19772591a8a6dfaa30c0bd38344"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.8-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.25"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.8-SNAPSHOT.jar",
          "url": "megameklab-0.49.8-SNAPSHOT.jar",
          "size": 1042789,
          "sha512": "ed86edfe5f065771dc77781816a0dc81a3933a1e1d4d7eeada732581df104750ba1e5c32bbbf866e0cdcda20b5273608be84dafee2ea0c00b5ad93c772b40c21",
          "sha256": "c1c95a31370f18634f3ed7619fa0dc3832d2f1daefaefcaddeb6bf0030524841",
          "sha1": "e4c754149fbec1d961fc67e5070e7dc53f77d1cf",
          "md5": "f59cd19772591a8a6dfaa30c0bd38344"
        }
      ]
    }
  ]
}
