{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8164222,
          "sha512": "eb32417d2499e5c5aff9ac83b18b528dbe1eec06eee2f1db1b33e9f4a61afe385211f36fa36023c57e4d561e55096461ee55716b9e4042fa7bb834659ce91f85",
          "sha256": "ce70bce8263bffbf50ffc8e06220b9c604bd73f5d3e363663d33118701895950",
          "sha1": "5f055aaaa7cfe804d184ca248fec94bb8de2b9dc",
          "md5": "03f6e10af72f87737e1476596a6f1b24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8164222,
          "sha512": "eb32417d2499e5c5aff9ac83b18b528dbe1eec06eee2f1db1b33e9f4a61afe385211f36fa36023c57e4d561e55096461ee55716b9e4042fa7bb834659ce91f85",
          "sha256": "ce70bce8263bffbf50ffc8e06220b9c604bd73f5d3e363663d33118701895950",
          "sha1": "5f055aaaa7cfe804d184ca248fec94bb8de2b9dc",
          "md5": "03f6e10af72f87737e1476596a6f1b24"
        }
      ]
    }
  ]
}
