{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8202761,
          "sha512": "87c69fc363e51df74df59606e1804bbcfac9c90e822dee4931d24d2302c1497c744c080e55b0bc39109026a67596fbc6b3b7e9fca80734b520577a95d3453942",
          "sha256": "e2578c572455a0a1c0019fc996b811b872e6f80e64ef9ec494ef318c91520091",
          "sha1": "8d512e66c0db57e122e7b622ae654bbf60c50258",
          "md5": "6e5b429a6477e4a7b1d8beca60b52eb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8202761,
          "sha512": "87c69fc363e51df74df59606e1804bbcfac9c90e822dee4931d24d2302c1497c744c080e55b0bc39109026a67596fbc6b3b7e9fca80734b520577a95d3453942",
          "sha256": "e2578c572455a0a1c0019fc996b811b872e6f80e64ef9ec494ef318c91520091",
          "sha1": "8d512e66c0db57e122e7b622ae654bbf60c50258",
          "md5": "6e5b429a6477e4a7b1d8beca60b52eb2"
        }
      ]
    }
  ]
}
