{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8156422,
          "sha512": "0e14d56391a22b3f8cb858e1256d6eae573206624adbeed59d73a4fa8ddf4e1881065a957d278ae612a834edf8e6ef96eec32aa32a38b1a542171e9f0c5509fc",
          "sha256": "645a05150773922209968f4378398e4f96303433ee29a51ad2cff23ed00e8f26",
          "sha1": "9eab3dfd3bef204cadfaff508eb64d9b267515c7",
          "md5": "37a0bcf7c6b15ae37b41ab277fb53c16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8156422,
          "sha512": "0e14d56391a22b3f8cb858e1256d6eae573206624adbeed59d73a4fa8ddf4e1881065a957d278ae612a834edf8e6ef96eec32aa32a38b1a542171e9f0c5509fc",
          "sha256": "645a05150773922209968f4378398e4f96303433ee29a51ad2cff23ed00e8f26",
          "sha1": "9eab3dfd3bef204cadfaff508eb64d9b267515c7",
          "md5": "37a0bcf7c6b15ae37b41ab277fb53c16"
        }
      ]
    }
  ]
}
