{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8199744,
          "sha512": "eb2ee1277421bb731cdcf10c3f0a8a10a932ecfd6208189dc0b9c1be43bf77f2e547285a851a186dfed16d02bcc8af24f5f3a3e7d166440ef52ff0852b4ec0ea",
          "sha256": "8a58242d1b2fdf1297a6e9d8426207c2935f1a75327939d25af7b42b1258d58b",
          "sha1": "d451c2d5aeaa7d1c3e9fe3434e08e6135b6c21b0",
          "md5": "fd029fefa0d5d35bb54c8e1bb40d746b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8199744,
          "sha512": "eb2ee1277421bb731cdcf10c3f0a8a10a932ecfd6208189dc0b9c1be43bf77f2e547285a851a186dfed16d02bcc8af24f5f3a3e7d166440ef52ff0852b4ec0ea",
          "sha256": "8a58242d1b2fdf1297a6e9d8426207c2935f1a75327939d25af7b42b1258d58b",
          "sha1": "d451c2d5aeaa7d1c3e9fe3434e08e6135b6c21b0",
          "md5": "fd029fefa0d5d35bb54c8e1bb40d746b"
        }
      ]
    }
  ]
}
