{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8200402,
          "sha512": "a6fb2359de9967d3f3cf96ace0543b9f58742d0f72d766d8431c138955485a152821c98020fa602235c48f654cbcf3e24c6084b64f7f411b7ed748cfc10d9ba5",
          "sha256": "7ed69d2ae6b22f5e85635d7603cc70ceecb69923ae4f3358ea3eb21b4c2d4d19",
          "sha1": "706db67b5c94d860a564f3f859c5b7258bb661ab",
          "md5": "7055049a7f2c565a46a06aaa3727ea9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.12-SNAPSHOT.jar",
          "url": "megamek-0.49.12-SNAPSHOT.jar",
          "size": 8200402,
          "sha512": "a6fb2359de9967d3f3cf96ace0543b9f58742d0f72d766d8431c138955485a152821c98020fa602235c48f654cbcf3e24c6084b64f7f411b7ed748cfc10d9ba5",
          "sha256": "7ed69d2ae6b22f5e85635d7603cc70ceecb69923ae4f3358ea3eb21b4c2d4d19",
          "sha1": "706db67b5c94d860a564f3f859c5b7258bb661ab",
          "md5": "7055049a7f2c565a46a06aaa3727ea9b"
        }
      ]
    }
  ]
}
