{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ehqft3dka5c6hf3g4hkfg2ubmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.9-SNAPSHOT.jar",
          "url": "mekhq-0.49.9-SNAPSHOT.jar",
          "size": 3864143,
          "sha512": "98569f36a9ba1e1d622fae8a04acf9f11b359f19446ecae9f6d8b694f2f5c68cda4a2d1bc8c244b9b3a860a93a166ed018baf0b77644d3aa5120f761a95ceb39",
          "sha256": "20f8364c9c00f9160ce3d7e061342935d4fb65ffa1b0604605d236166146116c",
          "sha1": "a6f7696a358d05d356bc84873d731a3ce8d7ea90",
          "md5": "71cc5e77ed6e72e4ac7eb7e37816c27f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.9-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.14"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.9-SNAPSHOT.jar",
          "url": "mekhq-0.49.9-SNAPSHOT.jar",
          "size": 3864143,
          "sha512": "98569f36a9ba1e1d622fae8a04acf9f11b359f19446ecae9f6d8b694f2f5c68cda4a2d1bc8c244b9b3a860a93a166ed018baf0b77644d3aa5120f761a95ceb39",
          "sha256": "20f8364c9c00f9160ce3d7e061342935d4fb65ffa1b0604605d236166146116c",
          "sha1": "a6f7696a358d05d356bc84873d731a3ce8d7ea90",
          "md5": "71cc5e77ed6e72e4ac7eb7e37816c27f"
        }
      ]
    }
  ]
}
