{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fnz2sj3u3reilnepwxl6n5hfkq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.7-SNAPSHOT.jar",
          "url": "megameklab-0.49.7-SNAPSHOT.jar",
          "size": 1089325,
          "sha512": "03cf75138d3ce066f125133ba66530e44b2a4e75875fb672bb879900b4a0bbdbfce1d4be16308ddced5b0260bf65155d8197c34386b345685ca56ca3043a886a",
          "sha256": "852de848881a46df7f0febbf0474b27e256370f5b1617ea32e3d875b08223722",
          "sha1": "4557feb07e50d9244dfea47d537b60086bab3d2d",
          "md5": "3b23e4ddba18247f83c6872ef44c3303"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.7-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.24"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.7-SNAPSHOT.jar",
          "url": "megameklab-0.49.7-SNAPSHOT.jar",
          "size": 1089325,
          "sha512": "03cf75138d3ce066f125133ba66530e44b2a4e75875fb672bb879900b4a0bbdbfce1d4be16308ddced5b0260bf65155d8197c34386b345685ca56ca3043a886a",
          "sha256": "852de848881a46df7f0febbf0474b27e256370f5b1617ea32e3d875b08223722",
          "sha1": "4557feb07e50d9244dfea47d537b60086bab3d2d",
          "md5": "3b23e4ddba18247f83c6872ef44c3303"
        }
      ]
    }
  ]
}
