{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pbqeasubpratld3ipb3qof5wim"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6.jar",
          "url": "megamek-0.49.6.jar",
          "size": 7393549,
          "sha512": "854fe1f8c11478a43e20863f8887fd3e7216f2296175eca92ca13e94c5eccf3c8a27a34dade18236c31b59b135d619080c3e470bd67760ca7fd0cefc5ca9469d",
          "sha256": "e2de3166fc718b2385633e0e90d96a496f4831d12855cd9ba83b6d64306e0a5f",
          "sha1": "7d32e9eac5f6a9bcbd6904b4da19dee7a04a5575",
          "md5": "36c177fbe009bead2a1ed6d20738280f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6.jar",
          "url": "megamek-0.49.6.jar",
          "size": 7393549,
          "sha512": "854fe1f8c11478a43e20863f8887fd3e7216f2296175eca92ca13e94c5eccf3c8a27a34dade18236c31b59b135d619080c3e470bd67760ca7fd0cefc5ca9469d",
          "sha256": "e2de3166fc718b2385633e0e90d96a496f4831d12855cd9ba83b6d64306e0a5f",
          "sha1": "7d32e9eac5f6a9bcbd6904b4da19dee7a04a5575",
          "md5": "36c177fbe009bead2a1ed6d20738280f"
        }
      ]
    }
  ]
}
