{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.17.jar",
          "url": "megamek-0.49.17.jar",
          "size": 8498700,
          "sha512": "cd5dd0f9f779873525be65ddff555a1dda44ff1a5463c1bd13685587c4d86c52a38e4832bff1b2e42bd2d7524e0a57b4a64fbd7bdec5dfd7c58f6b6cadeed941",
          "sha256": "bb113e924bb8f368372798107ec2eea7219e8fdb3ad79a1239d3b929c60f1621",
          "sha1": "215a9b7ce7b6901a5470e50ff25b0b2257c07b8c",
          "md5": "a3ab5652f75c33ea6747db20a25add85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.17.jar",
          "url": "megamek-0.49.17.jar",
          "size": 8498700,
          "sha512": "cd5dd0f9f779873525be65ddff555a1dda44ff1a5463c1bd13685587c4d86c52a38e4832bff1b2e42bd2d7524e0a57b4a64fbd7bdec5dfd7c58f6b6cadeed941",
          "sha256": "bb113e924bb8f368372798107ec2eea7219e8fdb3ad79a1239d3b929c60f1621",
          "sha1": "215a9b7ce7b6901a5470e50ff25b0b2257c07b8c",
          "md5": "a3ab5652f75c33ea6747db20a25add85"
        }
      ]
    }
  ]
}
