{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.17.jar",
          "url": "megamek-0.49.17.jar",
          "size": 8497096,
          "sha512": "4c6310688ceecef0f6fe27d5d7d281b3f4f0727338004bc30239e7bd4c5e0d8f011f80ef58ecae4e5cb4594ec0159e365e0cd56d8f3c03b985aaaedab5a69dcb",
          "sha256": "a4c23301bcc84566ce9db07ef18623fd162b90aa7b22828302eb59a2534550fb",
          "sha1": "5d0e4fd42bfe95c51122371461f04d3b60ab5da3",
          "md5": "6ce8414f7ab8c2208353b8c4131d0b9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.17.jar",
          "url": "megamek-0.49.17.jar",
          "size": 8497096,
          "sha512": "4c6310688ceecef0f6fe27d5d7d281b3f4f0727338004bc30239e7bd4c5e0d8f011f80ef58ecae4e5cb4594ec0159e365e0cd56d8f3c03b985aaaedab5a69dcb",
          "sha256": "a4c23301bcc84566ce9db07ef18623fd162b90aa7b22828302eb59a2534550fb",
          "sha1": "5d0e4fd42bfe95c51122371461f04d3b60ab5da3",
          "md5": "6ce8414f7ab8c2208353b8c4131d0b9e"
        }
      ]
    }
  ]
}
