{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16.jar",
          "url": "megamek-0.49.16.jar",
          "size": 8491569,
          "sha512": "e53a05aa6d34c73fd74469154044559741ced56deace582930d1a91271260aec6e4c8ddce64b7b2075f13b972ef7da685fb9da2bce17de42bb6f6f87b3884055",
          "sha256": "03a63ea7e381b74fa92bdbe5ef6ffcf4a24e0f45e9f1522a77d791aea9dfa05d",
          "sha1": "3a35663841f75008af3908aa11367995c4db1bf9",
          "md5": "4286af95049e55d74a80d8dbb1aef797"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16.jar",
          "url": "megamek-0.49.16.jar",
          "size": 8491569,
          "sha512": "e53a05aa6d34c73fd74469154044559741ced56deace582930d1a91271260aec6e4c8ddce64b7b2075f13b972ef7da685fb9da2bce17de42bb6f6f87b3884055",
          "sha256": "03a63ea7e381b74fa92bdbe5ef6ffcf4a24e0f45e9f1522a77d791aea9dfa05d",
          "sha1": "3a35663841f75008af3908aa11367995c4db1bf9",
          "md5": "4286af95049e55d74a80d8dbb1aef797"
        }
      ]
    }
  ]
}
