{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16.jar",
          "url": "megamek-0.49.16.jar",
          "size": 8498654,
          "sha512": "8d01ffa16c9208945bedf29a4c547ff3126803f880b852a4f7411d4abd9776ec78fcbb0e25422521a05dc68acd930b4f5d51ced8a39b37bd644330582deaab47",
          "sha256": "2d26200c52481a708eedb6f8a4ed04a75c1042d4cef40955cdeb4c77424ba091",
          "sha1": "fee7b4b2aaa9b1e235ebba6c967f6dbe79998c4a",
          "md5": "c4983202f19150bb4cd3e8ba91118ed6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16.jar",
          "url": "megamek-0.49.16.jar",
          "size": 8498654,
          "sha512": "8d01ffa16c9208945bedf29a4c547ff3126803f880b852a4f7411d4abd9776ec78fcbb0e25422521a05dc68acd930b4f5d51ced8a39b37bd644330582deaab47",
          "sha256": "2d26200c52481a708eedb6f8a4ed04a75c1042d4cef40955cdeb4c77424ba091",
          "sha1": "fee7b4b2aaa9b1e235ebba6c967f6dbe79998c4a",
          "md5": "c4983202f19150bb4cd3e8ba91118ed6"
        }
      ]
    }
  ]
}
