{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.16.jar",
          "url": "megamek-0.49.16.jar",
          "size": 8497047,
          "sha512": "cc61bd4c52b17781633d4de665611e4b38aca818166779757ab7b0c479cea1525ec1efd3acc909188888b49a8e8fcdd2f705d465c5fd28dc0c52e01d70693a5e",
          "sha256": "bd4039dbaa257fdb31b0c277dce198840f6f91feaa5a4681a5be7a0eae5dd3ed",
          "sha1": "766a54a8bd0d6ba2b11c16a3ade8175613859853",
          "md5": "bb8c541df2148fd1428b602d92f36834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.16.jar",
          "url": "megamek-0.49.16.jar",
          "size": 8497047,
          "sha512": "cc61bd4c52b17781633d4de665611e4b38aca818166779757ab7b0c479cea1525ec1efd3acc909188888b49a8e8fcdd2f705d465c5fd28dc0c52e01d70693a5e",
          "sha256": "bd4039dbaa257fdb31b0c277dce198840f6f91feaa5a4681a5be7a0eae5dd3ed",
          "sha1": "766a54a8bd0d6ba2b11c16a3ade8175613859853",
          "md5": "bb8c541df2148fd1428b602d92f36834"
        }
      ]
    }
  ]
}
