{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "67ozmkgjyfcc5h4mqv4ycbwsvm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7482819,
          "sha512": "d1cae71465339967a7e5331a6203e1015e244b7846cfc8daa3bd3fd812260c59fdd5f69efc6d6f25e7e4d2c7fea18f679a0aeb2e28e24d8124f507b7b5d03819",
          "sha256": "63b8ca53628c8ea89616a6d4b1b880a64ff42d119cb6a47ed4345562681060f9",
          "sha1": "6d527631ab44f3dc08006e629bbaa24733b50ac6",
          "md5": "a9f067be80eb7e5d6f36eb0d8d6dc74a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7482819,
          "sha512": "d1cae71465339967a7e5331a6203e1015e244b7846cfc8daa3bd3fd812260c59fdd5f69efc6d6f25e7e4d2c7fea18f679a0aeb2e28e24d8124f507b7b5d03819",
          "sha256": "63b8ca53628c8ea89616a6d4b1b880a64ff42d119cb6a47ed4345562681060f9",
          "sha1": "6d527631ab44f3dc08006e629bbaa24733b50ac6",
          "md5": "a9f067be80eb7e5d6f36eb0d8d6dc74a"
        }
      ]
    }
  ]
}
