{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "by73wnphzvh7zhbjh2xffzpht4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7483601,
          "sha512": "3150637e5d340812ed1f980442a6a6b1b3e6ec508b12be6712a1d6ea20fdbf9a6eb52b1059b3857f00dc6d63e4840180bc2498dd89fa9281bef24c5261bc6bc6",
          "sha256": "2beae43a0eb56e0b9fe790b495c6e887982aabdaad9ee03e5148fb7df99cd030",
          "sha1": "c879b64918d91a82c1d0c2b3ce63e1f11f55ed26",
          "md5": "ebb024a899aa4b19a89105bb6e6e5270"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7483601,
          "sha512": "3150637e5d340812ed1f980442a6a6b1b3e6ec508b12be6712a1d6ea20fdbf9a6eb52b1059b3857f00dc6d63e4840180bc2498dd89fa9281bef24c5261bc6bc6",
          "sha256": "2beae43a0eb56e0b9fe790b495c6e887982aabdaad9ee03e5148fb7df99cd030",
          "sha1": "c879b64918d91a82c1d0c2b3ce63e1f11f55ed26",
          "md5": "ebb024a899aa4b19a89105bb6e6e5270"
        }
      ]
    }
  ]
}
