{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6jxfsrkmafhtrlj74aejl6wgi4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7476783,
          "sha512": "2dc43d613a868ee775f1e7a737d8013e09dabe0492103a6d9b8f83f3bc7c977010bfa4d62ece5ed5cf94cb6275e89b0e3241896ff8cca8c8c643de685da4489f",
          "sha256": "34c9b3a3cae1a1268dc2f2d65fd070e4ba5b23dc3b69c07ea9199f64c706f013",
          "sha1": "d9d7d684f100d83c023aab2f4c05d628ed4331dd",
          "md5": "b030b439fe536e6657b25b608ea9ddbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7476783,
          "sha512": "2dc43d613a868ee775f1e7a737d8013e09dabe0492103a6d9b8f83f3bc7c977010bfa4d62ece5ed5cf94cb6275e89b0e3241896ff8cca8c8c643de685da4489f",
          "sha256": "34c9b3a3cae1a1268dc2f2d65fd070e4ba5b23dc3b69c07ea9199f64c706f013",
          "sha1": "d9d7d684f100d83c023aab2f4c05d628ed4331dd",
          "md5": "b030b439fe536e6657b25b608ea9ddbf"
        }
      ]
    }
  ]
}
