{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "k2u5npfb55esvft3al3txrpeuy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7393648,
          "sha512": "5dc91ec6b775707d0b73551d916674704f3f246267c8adb33d5ac9522b48c992f170442f4d992b797c2d3aa6cb89ed9d12321b763d44879a76d9b045b311a23d",
          "sha256": "63209af5e5bd22683ae181ffc7777dd70575d3ab6dada382968d79f95eadbb91",
          "sha1": "ca20600991d83051520c902ad6ba9208d6d786e6",
          "md5": "2bf69dd9276535cd776c618e7f8a4eec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7393648,
          "sha512": "5dc91ec6b775707d0b73551d916674704f3f246267c8adb33d5ac9522b48c992f170442f4d992b797c2d3aa6cb89ed9d12321b763d44879a76d9b045b311a23d",
          "sha256": "63209af5e5bd22683ae181ffc7777dd70575d3ab6dada382968d79f95eadbb91",
          "sha1": "ca20600991d83051520c902ad6ba9208d6d786e6",
          "md5": "2bf69dd9276535cd776c618e7f8a4eec"
        }
      ]
    }
  ]
}
