{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "2pzmkgnzkfge7do5pcequkvohq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7483304,
          "sha512": "3fb5c3a4a88cae320378f4ba2f0b5907806aba8c3bcb14eb7fda23c063d9ea98480e7dc2304e8fb54024a75288757b3c3d26f1944c7a1c0e219daa228aaeca5c",
          "sha256": "19e6b4c49b96ec1016095bd988697d44d8b7f93849d47bf1c655d0c22e21957b",
          "sha1": "70a84bdee7a56206943ef8ba8e6d6eea383a34f2",
          "md5": "4c1ab219597d9d2aa15cb4e453022993"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7483304,
          "sha512": "3fb5c3a4a88cae320378f4ba2f0b5907806aba8c3bcb14eb7fda23c063d9ea98480e7dc2304e8fb54024a75288757b3c3d26f1944c7a1c0e219daa228aaeca5c",
          "sha256": "19e6b4c49b96ec1016095bd988697d44d8b7f93849d47bf1c655d0c22e21957b",
          "sha1": "70a84bdee7a56206943ef8ba8e6d6eea383a34f2",
          "md5": "4c1ab219597d9d2aa15cb4e453022993"
        }
      ]
    }
  ]
}
