{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xu33dxgb6nfkxfthijexxhjyqy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7487649,
          "sha512": "6b909ddeec415d72c97f33d010a4a65a8ae1b2d26e76bb287770a35f97aec2ecf28c2abc23b0b7abe624325ab428000b03b4dbc07d04cddbccd5e2b3c08c48b6",
          "sha256": "1badf988ffef5ccf9f4b23f69d75bcf74e93213ac039ef01672e097c41499b91",
          "sha1": "1129bc2b14e529d37820420f830a95f553511667",
          "md5": "a08c68f9335e3d2e3aa0ac7ddb4702d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7487649,
          "sha512": "6b909ddeec415d72c97f33d010a4a65a8ae1b2d26e76bb287770a35f97aec2ecf28c2abc23b0b7abe624325ab428000b03b4dbc07d04cddbccd5e2b3c08c48b6",
          "sha256": "1badf988ffef5ccf9f4b23f69d75bcf74e93213ac039ef01672e097c41499b91",
          "sha1": "1129bc2b14e529d37820420f830a95f553511667",
          "md5": "a08c68f9335e3d2e3aa0ac7ddb4702d0"
        }
      ]
    }
  ]
}
