{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "hs7jksbv7faepillaevw6cg2lu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7393666,
          "sha512": "e5e538b24b3f9245f0f59a751d981d36444e3b41d31ae5124fd46a06c13ba933071593e4cc678142f50a1ce4413fb64f0820c4b0b5bcbbecd5be8b353e030962",
          "sha256": "71b069b1ce7f7ad41c48a51bcaa44ebe32033dc7283dc41ff6205b8f02185a0b",
          "sha1": "b2fd84d66dad81c0096da3ffce062636c8dd3570",
          "md5": "51a5c5a30d573c2e59c1e22586714b68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7393666,
          "sha512": "e5e538b24b3f9245f0f59a751d981d36444e3b41d31ae5124fd46a06c13ba933071593e4cc678142f50a1ce4413fb64f0820c4b0b5bcbbecd5be8b353e030962",
          "sha256": "71b069b1ce7f7ad41c48a51bcaa44ebe32033dc7283dc41ff6205b8f02185a0b",
          "sha1": "b2fd84d66dad81c0096da3ffce062636c8dd3570",
          "md5": "51a5c5a30d573c2e59c1e22586714b68"
        }
      ]
    }
  ]
}
