{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "iseywvn3q5alpbwfwix2uukkrm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7483179,
          "sha512": "b7294cca782cc7c9fd21f4ae61d782ffadaae7618e5d4b6e00ed7e0626755c37970c7df5f2a63b217a34f5a73ebfe7ced9ec37eadcda2aeb7d1751a0b28f295c",
          "sha256": "d372f97d5586d3e9144ef2f5973419ec5c59cdeae81f2ede7905c65cfe17fc39",
          "sha1": "1eb00e0ae9f7c8ccee907cc010dbe76b15a1a920",
          "md5": "e0ce3d6f65960acb71c75613017f8858"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.28"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.6-SNAPSHOT.jar",
          "url": "megamek-0.49.6-SNAPSHOT.jar",
          "size": 7483179,
          "sha512": "b7294cca782cc7c9fd21f4ae61d782ffadaae7618e5d4b6e00ed7e0626755c37970c7df5f2a63b217a34f5a73ebfe7ced9ec37eadcda2aeb7d1751a0b28f295c",
          "sha256": "d372f97d5586d3e9144ef2f5973419ec5c59cdeae81f2ede7905c65cfe17fc39",
          "sha1": "1eb00e0ae9f7c8ccee907cc010dbe76b15a1a920",
          "md5": "e0ce3d6f65960acb71c75613017f8858"
        }
      ]
    }
  ]
}
