{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.10-SNAPSHOT.jar",
          "url": "mekhq-0.49.10-SNAPSHOT.jar",
          "size": 3892628,
          "sha512": "5975cbb4c19336ddd39568d2b5b5504b414432932bbab5b29e37380d32f7be567cbbfa313f28f5b50e1bb5a173387c3852b936455b26bf6c7479afe9a21de812",
          "sha256": "a0eb21ffd4c6661101ec9ab15e527ef2e9a6911975408e1360f5b8a7dac4a7c1",
          "sha1": "e0cb2aa3e222a4f8c7422dc277cee4fac8b72f3b",
          "md5": "206730f266ef49cabd6cbb28747de884"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.10-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.10-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.10-SNAPSHOT.jar",
          "url": "mekhq-0.49.10-SNAPSHOT.jar",
          "size": 3892628,
          "sha512": "5975cbb4c19336ddd39568d2b5b5504b414432932bbab5b29e37380d32f7be567cbbfa313f28f5b50e1bb5a173387c3852b936455b26bf6c7479afe9a21de812",
          "sha256": "a0eb21ffd4c6661101ec9ab15e527ef2e9a6911975408e1360f5b8a7dac4a7c1",
          "sha1": "e0cb2aa3e222a4f8c7422dc277cee4fac8b72f3b",
          "md5": "206730f266ef49cabd6cbb28747de884"
        }
      ]
    }
  ]
}
