{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.18-SNAPSHOT.jar",
          "url": "mekhq-0.49.18-SNAPSHOT.jar",
          "size": 3969161,
          "sha512": "3d9e81edbbb81d7438577a3cd82ba9fc32d21a60f7a87a004a44f56fcf4974582dd6da310aa1c039e558a3c43860a23c64fa449c572d8d902659a2edcd24bbb3",
          "sha256": "d8b916dbb35e4032208b6a21a1966674c5491fe8f6e55f00bdc9ddfb534a3d0c",
          "sha1": "f17933dd9b822bf1d853373b2009514075d141bd",
          "md5": "0e9e4da142fa405437353bc401ad4ad8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.18-SNAPSHOT"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.18-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.18-SNAPSHOT.jar",
          "url": "mekhq-0.49.18-SNAPSHOT.jar",
          "size": 3969161,
          "sha512": "3d9e81edbbb81d7438577a3cd82ba9fc32d21a60f7a87a004a44f56fcf4974582dd6da310aa1c039e558a3c43860a23c64fa449c572d8d902659a2edcd24bbb3",
          "sha256": "d8b916dbb35e4032208b6a21a1966674c5491fe8f6e55f00bdc9ddfb534a3d0c",
          "sha1": "f17933dd9b822bf1d853373b2009514075d141bd",
          "md5": "0e9e4da142fa405437353bc401ad4ad8"
        }
      ]
    }
  ]
}
