{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "svk7illyqje5vmj27t5fnp44pi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.8.jar",
          "url": "megameklab-0.49.8.jar",
          "size": 1042078,
          "sha512": "ccbb547866c838b2d7e514c1ae321167bac0c7180937be04ee8ff36159ba229e37f5c41bfe05288cc8b0bc223be92c2c8b81a568414efc85042a50dc0055c620",
          "sha256": "07af082b4d785962544ff482ac119b6f601fa689de35361ccebb1861646675cb",
          "sha1": "c0ec320a94c1fa182f4968da11216c0df4db0111",
          "md5": "4e4f741070510f583846bafd1335eeb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.8"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.26"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.8.jar",
          "url": "megameklab-0.49.8.jar",
          "size": 1042078,
          "sha512": "ccbb547866c838b2d7e514c1ae321167bac0c7180937be04ee8ff36159ba229e37f5c41bfe05288cc8b0bc223be92c2c8b81a568414efc85042a50dc0055c620",
          "sha256": "07af082b4d785962544ff482ac119b6f601fa689de35361ccebb1861646675cb",
          "sha1": "c0ec320a94c1fa182f4968da11216c0df4db0111",
          "md5": "4e4f741070510f583846bafd1335eeb7"
        }
      ]
    }
  ]
}
