{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.20-SNAPSHOT.jar",
          "url": "megameklab-0.49.20-SNAPSHOT.jar",
          "size": 1113882,
          "sha512": "d958af576212660d01f4ad25e432f90624e637cff818835c80c986caedf7297e2f4f77cdb7f083af0e1154b0143ddffbf5914571560497e0c22fe29b8f38b8a7",
          "sha256": "bf2feed4f1f1a25e987e3a5177130f36b2c0cb75d2d4090bd0bf1bed849ef8bd",
          "sha1": "f31ea052d5d496a977a21e23c20013ac174966e4",
          "md5": "0d7f94f73359d328c06ea04ab8107e59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.20-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.20-SNAPSHOT.jar",
          "url": "megameklab-0.49.20-SNAPSHOT.jar",
          "size": 1113882,
          "sha512": "d958af576212660d01f4ad25e432f90624e637cff818835c80c986caedf7297e2f4f77cdb7f083af0e1154b0143ddffbf5914571560497e0c22fe29b8f38b8a7",
          "sha256": "bf2feed4f1f1a25e987e3a5177130f36b2c0cb75d2d4090bd0bf1bed849ef8bd",
          "sha1": "f31ea052d5d496a977a21e23c20013ac174966e4",
          "md5": "0d7f94f73359d328c06ea04ab8107e59"
        }
      ]
    }
  ]
}
