{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8356309,
          "sha512": "f35f9cb99cbbaa81a9fc7b1a708d6af67dc07ad93673b3abc68d0b96ee6a3203d07ac80862fccdcb194d29d3db958c4efea40a5451f16e8eaca21d4ea7d56b74",
          "sha256": "da832f07cf99e99b312b4380793bd1d7f00be18b60bf66dd1491e623c47d8d49",
          "sha1": "82007ecf6423ce8e47fa5aec786b1f626638fd17",
          "md5": "3876c9340c2cd60936669be8b13a6b64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8356309,
          "sha512": "f35f9cb99cbbaa81a9fc7b1a708d6af67dc07ad93673b3abc68d0b96ee6a3203d07ac80862fccdcb194d29d3db958c4efea40a5451f16e8eaca21d4ea7d56b74",
          "sha256": "da832f07cf99e99b312b4380793bd1d7f00be18b60bf66dd1491e623c47d8d49",
          "sha1": "82007ecf6423ce8e47fa5aec786b1f626638fd17",
          "md5": "3876c9340c2cd60936669be8b13a6b64"
        }
      ]
    }
  ]
}
