{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8414940,
          "sha512": "1e61a5c39d656fb0621605c89e26220465efc6ef53f6e64469339e6a9fb3bb25baf7cd322cf18d27b0e4114ab20912f412262aa608b947080f74f114766f44b3",
          "sha256": "c130ac4e8801adb1be99cc655480f9e0bc66c1f0f4ddb51b2655109f5eae4bfe",
          "sha1": "da0d369b12924ef17d7377e72dae504cfd12983a",
          "md5": "7d324d63cd7aab19ef99ffd8179a3ead"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8414940,
          "sha512": "1e61a5c39d656fb0621605c89e26220465efc6ef53f6e64469339e6a9fb3bb25baf7cd322cf18d27b0e4114ab20912f412262aa608b947080f74f114766f44b3",
          "sha256": "c130ac4e8801adb1be99cc655480f9e0bc66c1f0f4ddb51b2655109f5eae4bfe",
          "sha1": "da0d369b12924ef17d7377e72dae504cfd12983a",
          "md5": "7d324d63cd7aab19ef99ffd8179a3ead"
        }
      ]
    }
  ]
}
