{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8398182,
          "sha512": "6a11bdbebd46ad799cc60ec8491b59358ca8eeab84150e0d64bc951e4be20be101bcff40cb205470866933b5236d2b3e20e50bbe7b113be31a54d437b96f098e",
          "sha256": "c5714de03de1e515e4d5a7507ef99f6954a4528b008a24f5fa1dd573597d90c8",
          "sha1": "db5ae48e12cbb1247c1f00cb436c345e9dea0343",
          "md5": "c68993dd23ca84d5c444a1d2f46aec7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8398182,
          "sha512": "6a11bdbebd46ad799cc60ec8491b59358ca8eeab84150e0d64bc951e4be20be101bcff40cb205470866933b5236d2b3e20e50bbe7b113be31a54d437b96f098e",
          "sha256": "c5714de03de1e515e4d5a7507ef99f6954a4528b008a24f5fa1dd573597d90c8",
          "sha1": "db5ae48e12cbb1247c1f00cb436c345e9dea0343",
          "md5": "c68993dd23ca84d5c444a1d2f46aec7e"
        }
      ]
    }
  ]
}
