{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8426349,
          "sha512": "492741629c38d4d6a11bf915c00b9da4ce3e9d89e119cd38dc60795664d0c5caf5b90d0befd00aa5040fbf21f2102650cecb06face3c8233ec13c6c8caddb125",
          "sha256": "1c7eebf800f5c7ad04e382cf14bb7c039e3948aca2d474008d177bbeca610335",
          "sha1": "6026f95fb1bd809163ba874685a19b1f0033f448",
          "md5": "2b7cdb3d878846d842c7b10c236c6412"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8426349,
          "sha512": "492741629c38d4d6a11bf915c00b9da4ce3e9d89e119cd38dc60795664d0c5caf5b90d0befd00aa5040fbf21f2102650cecb06face3c8233ec13c6c8caddb125",
          "sha256": "1c7eebf800f5c7ad04e382cf14bb7c039e3948aca2d474008d177bbeca610335",
          "sha1": "6026f95fb1bd809163ba874685a19b1f0033f448",
          "md5": "2b7cdb3d878846d842c7b10c236c6412"
        }
      ]
    }
  ]
}
