{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8426058,
          "sha512": "e56ccc7d711c48241fe84cfcaa48c65ab7413c00a0b7fe47c5a8661dc56b97e5881296296d585853f8d707169e38c512e17146490c979db7cd03575dd4967d30",
          "sha256": "7b796019cb4569e1ca57eac5aa48d32e1eb42126704649f46f1f541f62058505",
          "sha1": "6bc76f37a1eac2c8bfe7821e3f0dfbb68f3d34ea",
          "md5": "8fb856d3bc81afd5b3c7c74c17f9f9c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.19"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.13-SNAPSHOT.jar",
          "url": "megamek-0.49.13-SNAPSHOT.jar",
          "size": 8426058,
          "sha512": "e56ccc7d711c48241fe84cfcaa48c65ab7413c00a0b7fe47c5a8661dc56b97e5881296296d585853f8d707169e38c512e17146490c979db7cd03575dd4967d30",
          "sha256": "7b796019cb4569e1ca57eac5aa48d32e1eb42126704649f46f1f541f62058505",
          "sha1": "6bc76f37a1eac2c8bfe7821e3f0dfbb68f3d34ea",
          "md5": "8fb856d3bc81afd5b3c7c74c17f9f9c6"
        }
      ]
    }
  ]
}
