{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab-mass-print-CGL",
    "version": "0.49.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-mass-print-CGL-0.49.20.jar",
          "url": "megameklab-mass-print-CGL-0.49.20.jar",
          "size": 1116980,
          "sha512": "e17170516cc06e7f6f46ce5e0575ea0297d177d7edd85098b741b6a90367518cdb1b59b757ff6146ff9e879cdf74b275912ce317e8da87b593f3d86db6ecb6a9",
          "sha256": "5c78eaa58b4cb685640a6ea46e35bcf81e2ce0fe6744ae4523dec2f7e1231078",
          "sha1": "5426e6c383347ebe608b7f9d057f95f230c9f6ff",
          "md5": "a307a48a746225cc9f0f0ab83498b8c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-mass-print-CGL-0.49.20.jar",
          "url": "megameklab-mass-print-CGL-0.49.20.jar",
          "size": 1116980,
          "sha512": "e17170516cc06e7f6f46ce5e0575ea0297d177d7edd85098b741b6a90367518cdb1b59b757ff6146ff9e879cdf74b275912ce317e8da87b593f3d86db6ecb6a9",
          "sha256": "5c78eaa58b4cb685640a6ea46e35bcf81e2ce0fe6744ae4523dec2f7e1231078",
          "sha1": "5426e6c383347ebe608b7f9d057f95f230c9f6ff",
          "md5": "a307a48a746225cc9f0f0ab83498b8c7"
        }
      ]
    }
  ]
}
