{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "z35vhzystbd6xk5ijyat6b2x6u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7762041,
          "sha512": "3842eda9444768bba376ce5bfd57ef870e9fb55dd78b00121c874ab9bdd9c996ebcde69892cf1ce4ae0ac4d9c9bcdec1fa8952d4770c08a8e0fdc03bb30b881b",
          "sha256": "ad14a878bdafea1ec09bf5dd2e64e7b1ba4761b3af2f8a09010f5f112c5493c5",
          "sha1": "5a3fe0e3281f52fac8ef1764b0ba5d267399d50b",
          "md5": "d88f400054788b456bb7c6521739403f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7762041,
          "sha512": "3842eda9444768bba376ce5bfd57ef870e9fb55dd78b00121c874ab9bdd9c996ebcde69892cf1ce4ae0ac4d9c9bcdec1fa8952d4770c08a8e0fdc03bb30b881b",
          "sha256": "ad14a878bdafea1ec09bf5dd2e64e7b1ba4761b3af2f8a09010f5f112c5493c5",
          "sha1": "5a3fe0e3281f52fac8ef1764b0ba5d267399d50b",
          "md5": "d88f400054788b456bb7c6521739403f"
        }
      ]
    }
  ]
}
