{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "npdorkdr6ffznhjfdoiydgvsnm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7618876,
          "sha512": "9f09b673d000b3864aa5cdc12d8963ae9388244005e32489696f3458dbf48a923199563fc250b2f7d7ebfd92d55130c3025b723da9b137c468d82a1ebd1a11bb",
          "sha256": "a30a651108f2005b4ff039038f68f267b172217273c9b6f5345d2635a6cadf82",
          "sha1": "5ef4fe6be0e764d108d2a849655ac430e663a043",
          "md5": "dd00f5c1c71022c980f287891a434c1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7618876,
          "sha512": "9f09b673d000b3864aa5cdc12d8963ae9388244005e32489696f3458dbf48a923199563fc250b2f7d7ebfd92d55130c3025b723da9b137c468d82a1ebd1a11bb",
          "sha256": "a30a651108f2005b4ff039038f68f267b172217273c9b6f5345d2635a6cadf82",
          "sha1": "5ef4fe6be0e764d108d2a849655ac430e663a043",
          "md5": "dd00f5c1c71022c980f287891a434c1c"
        }
      ]
    }
  ]
}
