{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "oy2tysfpojhstaovrd5xkkmpxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7624647,
          "sha512": "3dad4b98f3facdcd82dd9db1a6b28fb57ce51f4e4bbd20bbb83f6b275dbdb652311e33c25269030cf5f0e20360af4b6e7382391c8e7ef6436d8395bd7a4323e2",
          "sha256": "4abf2282ca6b4a0e128e7b01fed39d15f2f3ee26b944ae1dc6c61807d9f6eedb",
          "sha1": "4ebadf7bf200500634e53fcb1e7e85b2441c94db",
          "md5": "3a2bac0c4cf70b68fcbfe3eaed5f961b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7624647,
          "sha512": "3dad4b98f3facdcd82dd9db1a6b28fb57ce51f4e4bbd20bbb83f6b275dbdb652311e33c25269030cf5f0e20360af4b6e7382391c8e7ef6436d8395bd7a4323e2",
          "sha256": "4abf2282ca6b4a0e128e7b01fed39d15f2f3ee26b944ae1dc6c61807d9f6eedb",
          "sha1": "4ebadf7bf200500634e53fcb1e7e85b2441c94db",
          "md5": "3a2bac0c4cf70b68fcbfe3eaed5f961b"
        }
      ]
    }
  ]
}
