{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "b7grye7eqrfdljwfb7s62nv46m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7631467,
          "sha512": "4f4f62c95c285eb94f6f1a2897129ae386fbe11cf3c75ab457b74b1b660219e26aef5e43359bf6bb3fe5dee7a7ec8984271454ed8c83303a4f9d8db0764664dc",
          "sha256": "e82f15b72916a244a2212279402c6e2250ab0b0bd7b4357c62a86ba8b5b71986",
          "sha1": "5506aaaad1285b2d2c4289c325bf4eefd8076a1d",
          "md5": "8f3aefe63bf793ff8d3f56ac7f4b0c05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7631467,
          "sha512": "4f4f62c95c285eb94f6f1a2897129ae386fbe11cf3c75ab457b74b1b660219e26aef5e43359bf6bb3fe5dee7a7ec8984271454ed8c83303a4f9d8db0764664dc",
          "sha256": "e82f15b72916a244a2212279402c6e2250ab0b0bd7b4357c62a86ba8b5b71986",
          "sha1": "5506aaaad1285b2d2c4289c325bf4eefd8076a1d",
          "md5": "8f3aefe63bf793ff8d3f56ac7f4b0c05"
        }
      ]
    }
  ]
}
