{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "hpqnm3yva5fyxf2o2ud32tpyre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7624186,
          "sha512": "6978c8e5642956824421462dfd8519313ef2aa9a7bc3a9781e2e961047402a74492843155bcdc5f7484ed9cdb4a99c07b5b16aac4f1f90f258a1bc33b6c54de2",
          "sha256": "1484ce3b5d15a55dfef2a5238be72fe6e396f5f0b9c295bdb1967dad3d1c18a5",
          "sha1": "f0994db60af3ef2bdab65b2ea8659c36636cb77a",
          "md5": "1b3f3689ea09dfa085f2f2e67874d361"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0-M4"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7624186,
          "sha512": "6978c8e5642956824421462dfd8519313ef2aa9a7bc3a9781e2e961047402a74492843155bcdc5f7484ed9cdb4a99c07b5b16aac4f1f90f258a1bc33b6c54de2",
          "sha256": "1484ce3b5d15a55dfef2a5238be72fe6e396f5f0b9c295bdb1967dad3d1c18a5",
          "sha1": "f0994db60af3ef2bdab65b2ea8659c36636cb77a",
          "md5": "1b3f3689ea09dfa085f2f2e67874d361"
        }
      ]
    }
  ]
}
