{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pgjut4yc6vd4flba2mlmx4qqga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7755896,
          "sha512": "acf9f0a7406eeef870833f3d5557f2fc115877b5b2e0c77bf52d2d00c28feb63e0903ed360c2c84265ef5c7890a74d461fd4bb8d957bf446f7bfb30f4be2a93f",
          "sha256": "d2122bc966d0a56cda1d6ac7ba0a343876069e92e4616616e75f78a74b1096a7",
          "sha1": "c80054fa49a81c8ce446edf183b424ca159854ed",
          "md5": "ef96b788a4e2c32c949a94a7c9498460"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7755896,
          "sha512": "acf9f0a7406eeef870833f3d5557f2fc115877b5b2e0c77bf52d2d00c28feb63e0903ed360c2c84265ef5c7890a74d461fd4bb8d957bf446f7bfb30f4be2a93f",
          "sha256": "d2122bc966d0a56cda1d6ac7ba0a343876069e92e4616616e75f78a74b1096a7",
          "sha1": "c80054fa49a81c8ce446edf183b424ca159854ed",
          "md5": "ef96b788a4e2c32c949a94a7c9498460"
        }
      ]
    }
  ]
}
