{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "n2raqiv66bfojn4ihexb7aroxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7764251,
          "sha512": "19bfe66a81fb12193b71f8931ffd85b79aa30d3a482129d6fc7ce9a1f451bd7e1a6d5282077ef5f74b905c87b7d80119ec3159a575cea581c25ef8a67ae5e62e",
          "sha256": "fad4ff82feeca47da35cbea6b9f03567fea5f0eb6c2f3acc34d73278df975a0a",
          "sha1": "267af50216b1b8361bd0eddd08adbb6f28d18a53",
          "md5": "c03b4e958b745adc8c360ba4a0820b7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7764251,
          "sha512": "19bfe66a81fb12193b71f8931ffd85b79aa30d3a482129d6fc7ce9a1f451bd7e1a6d5282077ef5f74b905c87b7d80119ec3159a575cea581c25ef8a67ae5e62e",
          "sha256": "fad4ff82feeca47da35cbea6b9f03567fea5f0eb6c2f3acc34d73278df975a0a",
          "sha1": "267af50216b1b8361bd0eddd08adbb6f28d18a53",
          "md5": "c03b4e958b745adc8c360ba4a0820b7e"
        }
      ]
    }
  ]
}
