{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "3apdkk6f5rdcpmzww74dtm7tgy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7764589,
          "sha512": "26fe25845a1b2588acf783505e50fcefcc6e6384e275befed4fcd45429aec2988538295167d419ec4ee2ba6b870781ece1612e19f7315c9799261f279009dcd6",
          "sha256": "7cc91269b900339d1a6052cc701e5e7d730c3500cdd818ef7d7959056604a9bf",
          "sha1": "9a850285402380f3845a840293df72de5b24ba63",
          "md5": "842b5cdd16b548834bcdf859c6c26c25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7764589,
          "sha512": "26fe25845a1b2588acf783505e50fcefcc6e6384e275befed4fcd45429aec2988538295167d419ec4ee2ba6b870781ece1612e19f7315c9799261f279009dcd6",
          "sha256": "7cc91269b900339d1a6052cc701e5e7d730c3500cdd818ef7d7959056604a9bf",
          "sha1": "9a850285402380f3845a840293df72de5b24ba63",
          "md5": "842b5cdd16b548834bcdf859c6c26c25"
        }
      ]
    }
  ]
}
