{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "anxvhpa4pbde3ccoi47m4jdpgu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7764317,
          "sha512": "6fa31fca24e2df60934bcbab7b0a48dadb5da34d000fcf9fd950932aae44c601fc894f0a4080dbb7ae1cedfb41b012ed9572c2f87a2597ba58929dd4e8d6e591",
          "sha256": "a5a7b6b8b133af4713d31d8c2a3ab18f7e9fe620f192dd1d1cd4bfeb7ff2e845",
          "sha1": "a7610f196d675791ea3ff4c9ac5b00afe21c0e38",
          "md5": "f2a9ff930c8be6c6f7e4f2aa8192c0d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7764317,
          "sha512": "6fa31fca24e2df60934bcbab7b0a48dadb5da34d000fcf9fd950932aae44c601fc894f0a4080dbb7ae1cedfb41b012ed9572c2f87a2597ba58929dd4e8d6e591",
          "sha256": "a5a7b6b8b133af4713d31d8c2a3ab18f7e9fe620f192dd1d1cd4bfeb7ff2e845",
          "sha1": "a7610f196d675791ea3ff4c9ac5b00afe21c0e38",
          "md5": "f2a9ff930c8be6c6f7e4f2aa8192c0d8"
        }
      ]
    }
  ]
}
