{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "p3ajnmiw35bqtk7hgefc6cdus4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7631873,
          "sha512": "45f51139d8748e6af53ea4b7dbe55f9d788fb42723e38959be6bf9542b60bbe8a4fc797871c1a5f2bdf0fa458b8d5f81c92d8b8bdd04ed8ca837fc203d57575a",
          "sha256": "8b0c6b3022740bd1c84dc8b53a384eada091382ee4a0a86a1c9a5ee33fa8ebbd",
          "sha1": "c2f541a3969cfb9adfa177ad83f62a21856588c2",
          "md5": "73c3f4907fa0460d63ce471f13c58518"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.9-SNAPSHOT.jar",
          "url": "megamek-0.49.9-SNAPSHOT.jar",
          "size": 7631873,
          "sha512": "45f51139d8748e6af53ea4b7dbe55f9d788fb42723e38959be6bf9542b60bbe8a4fc797871c1a5f2bdf0fa458b8d5f81c92d8b8bdd04ed8ca837fc203d57575a",
          "sha256": "8b0c6b3022740bd1c84dc8b53a384eada091382ee4a0a86a1c9a5ee33fa8ebbd",
          "sha1": "c2f541a3969cfb9adfa177ad83f62a21856588c2",
          "md5": "73c3f4907fa0460d63ce471f13c58518"
        }
      ]
    }
  ]
}
