{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megameklab",
    "version": "0.49.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megameklab-0.49.16.jar",
          "url": "megameklab-0.49.16.jar",
          "size": 1066498,
          "sha512": "b2f58bc7b7186135343453dca3b6c738bc610e2cb6db4a9b528f89ca6f8b792c522d2429ca94adbb05509d966adf86934099d386ea748e84bd5efca0fd354d0e",
          "sha256": "70052bff81a9c8f9cbb2df64f5fc3a0f97f643d3c497d184af636b88fb7f9dee",
          "sha1": "17439492fcf47e716b602d484fdecad07c398217",
          "md5": "cd03ee945f09cf711a620490a47fd224"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.16"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.pdfbox",
          "module": "pdfbox",
          "version": {
            "requires": "2.0.27"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            },
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.14"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-rasterizer",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svggen",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "fop",
          "version": {
            "requires": "2.7"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "*"
            },
            {
              "group": "com.sun.media",
              "module": "jai-codec"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "xml-apis",
          "module": "xml-apis-ext",
          "version": {
            "requires": "1.3.04"
          }
        }
      ],
      "files": [
        {
          "name": "megameklab-0.49.16.jar",
          "url": "megameklab-0.49.16.jar",
          "size": 1066498,
          "sha512": "b2f58bc7b7186135343453dca3b6c738bc610e2cb6db4a9b528f89ca6f8b792c522d2429ca94adbb05509d966adf86934099d386ea748e84bd5efca0fd354d0e",
          "sha256": "70052bff81a9c8f9cbb2df64f5fc3a0f97f643d3c497d184af636b88fb7f9dee",
          "sha1": "17439492fcf47e716b602d484fdecad07c398217",
          "md5": "cd03ee945f09cf711a620490a47fd224"
        }
      ]
    }
  ]
}
