{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "mekhq",
    "version": "0.49.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mekhq-0.49.12.jar",
          "url": "mekhq-0.49.12.jar",
          "size": 3950047,
          "sha512": "47097dbb8a106f2421df3a1d9dec3e099747cb8ac84a1e745daec6c30638abeafbe3d7ef31662c9b046e7f595c0d6365e22cf1c53f163d56d214da22192920f5",
          "sha256": "1a6ae22a26fcffbf7f81d4e18a60dd1ff7cad0595981c54b92d6ad13360e4ad4",
          "sha1": "d9c69d78bc7edeb0977d8c14603d166fe1013d45",
          "md5": "12cc4fe13c22232a6b202aefa16ba51d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.megamek",
          "module": "megamek",
          "version": {
            "requires": "0.49.12"
          }
        },
        {
          "group": "org.megamek",
          "module": "megameklab",
          "version": {
            "requires": "0.49.12"
          },
          "excludes": [
            {
              "group": "org.megamek",
              "module": "megameklab"
            },
            {
              "group": "org.mozilla",
              "module": "rhino"
            },
            {
              "group": "org.python",
              "module": "jython"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.vecmath",
          "module": "vecmath",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jfree",
          "module": "jfreechart",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.joda",
          "module": "joda-money",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "mekhq-0.49.12.jar",
          "url": "mekhq-0.49.12.jar",
          "size": 3950047,
          "sha512": "47097dbb8a106f2421df3a1d9dec3e099747cb8ac84a1e745daec6c30638abeafbe3d7ef31662c9b046e7f595c0d6365e22cf1c53f163d56d214da22192920f5",
          "sha256": "1a6ae22a26fcffbf7f81d4e18a60dd1ff7cad0595981c54b92d6ad13360e4ad4",
          "sha1": "d9c69d78bc7edeb0977d8c14603d166fe1013d45",
          "md5": "12cc4fe13c22232a6b202aefa16ba51d"
        }
      ]
    }
  ]
}
