{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20.jar",
          "url": "megamek-0.49.20.jar",
          "size": 8815667,
          "sha512": "39f5d91794b3b7bf89db5679fcb3e60961b0ee565552680cdba4b7f30d4340302e4b0d50842a67dd4c8c22dbaaa702315c1ae5cc41c890c8af830f60a3d54023",
          "sha256": "12da417b28953b7a68474a01c16d60f943cadc1dc13a2f9f4ad17d70b5626f0b",
          "sha1": "f980d037488843322631d4ecea17fae4b8aa8385",
          "md5": "f67dd3cd6ab1a135b74b78256329d082"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.32"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf-extras",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20.jar",
          "url": "megamek-0.49.20.jar",
          "size": 8815667,
          "sha512": "39f5d91794b3b7bf89db5679fcb3e60961b0ee565552680cdba4b7f30d4340302e4b0d50842a67dd4c8c22dbaaa702315c1ae5cc41c890c8af830f60a3d54023",
          "sha256": "12da417b28953b7a68474a01c16d60f943cadc1dc13a2f9f4ad17d70b5626f0b",
          "sha1": "f980d037488843322631d4ecea17fae4b8aa8385",
          "md5": "f67dd3cd6ab1a135b74b78256329d082"
        }
      ]
    }
  ]
}
