{
  "formatVersion": "1.1",
  "component": {
    "group": "org.megamek",
    "module": "megamek",
    "version": "0.49.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "megamek-0.49.20.jar",
          "url": "megamek-0.49.20.jar",
          "size": 8814027,
          "sha512": "981c5d17a3298f3740cd52a084edf24b0f1092b26b24b8162a130d6c7506c8dcfe165fcc15cc7f5b010191511ae9b958f3364be2713d1ccb3a8800558a116092",
          "sha256": "5605491ddecb0b483c446e4bce4fd38bca21044c01419953f4ac740fb232267d",
          "sha1": "cd37a40f11dfeb3de0a7fac5ebba47cced7eca65",
          "md5": "1efd38b436c81635fae06d7fd6b99f72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "com.github.ikkisoft",
          "module": "SerialKiller",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.32"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf-extras",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "megamek-0.49.20.jar",
          "url": "megamek-0.49.20.jar",
          "size": 8814027,
          "sha512": "981c5d17a3298f3740cd52a084edf24b0f1092b26b24b8162a130d6c7506c8dcfe165fcc15cc7f5b010191511ae9b958f3364be2713d1ccb3a8800558a116092",
          "sha256": "5605491ddecb0b483c446e4bce4fd38bca21044c01419953f4ac740fb232267d",
          "sha1": "cd37a40f11dfeb3de0a7fac5ebba47cced7eca65",
          "md5": "1efd38b436c81635fae06d7fd6b99f72"
        }
      ]
    }
  ]
}
